# Prepping test data set

In [1]:
# imports
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import seaborn as sns

plt.style.use('fivethirtyeight')

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

from sklearn.linear_model import LogisticRegression, LinearRegression, Lasso, LassoCV, RidgeCV

from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict
from sklearn.preprocessing import StandardScaler
from sklearn import metrics

In [2]:
pd.set_option('display.max_columns', 999)

In [3]:
test = pd.read_csv('./datasets/test.csv', index_col='Id')
clean_train = pd.read_csv('./datasets/clean_train.csv', index_col='Id')

In [4]:
test.shape

(879, 79)

In [5]:
test.head()

,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Mas Vnr Area,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin SF 1,BsmtFin Type 2,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Heating,Heating QC,Central Air,Electrical,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,Kitchen Qual,TotRms AbvGrd,Functional,Fireplaces,Fireplace Qu,Garage Type,Garage Yr Blt,Garage Finish,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type
Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2658,902301120,190,RM,69.0,9142,Pave,Grvl,Reg,Lvl,AllPub,Inside,Gtl,OldTown,Norm,Norm,2fmCon,2Story,6,8,1910,1950,Gable,CompShg,AsbShng,AsbShng,None,0.0,TA,Fa,Stone,Fa,TA,No,Unf,0,Unf,0,1020,1020,GasA,Gd,N,FuseP,908,1020,0,1928,0,0,2,0,4,2,Fa,9,Typ,0,NaN,Detchd,1910.0,Unf,1,440,Po,Po,Y,0,60,112,0,0,0,NaN,NaN,NaN,0,4,2006,WD
2718,905108090,90,RL,NaN,9662,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Sawyer,Norm,Norm,Duplex,1Story,5,4,1977,1977,Gable,CompShg,Plywood,Plywood,None,0.0,TA,TA,CBlock,Gd,TA,No,Unf,0,Unf,0,1967,1967,GasA,TA,Y,SBrkr,1967,0,0,1967,0,0,2,0,6,2,TA,10,Typ,0,NaN,Attchd,1977.0,Fin,2,580,TA,TA,Y,170,0,0,0,0,0,NaN,NaN,NaN,0,8,2006,WD
2414,528218130,60,RL,58.0,17104,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,7,5,2006,2006,Gable,CompShg,VinylSd,VinylSd,None,0.0,Gd,TA,PConc,Gd,Gd,Av,GLQ,554,Unf,0,100,654,GasA,Ex,Y,SBrkr,664,832,0,1496,1,0,2,1,3,1,Gd,7,Typ,1,Gd,Attchd,2006.0,RFn,2,426,TA,TA,Y,100,24,0,0,0,0,NaN,NaN,NaN,0,9,2006,New
1989,902207150,30,RM,60.0,8520,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,OldTown,Norm,Norm,1Fam,1Story,5,6,1923,2006,Gable,CompShg,Wd Sdng,Wd Sdng,None,0.0,Gd,TA,CBlock,TA,TA,No,Unf,0,Unf,0,968,968,GasA,TA,Y,SBrkr,968,0,0,968,0,0,1,0,2,1,TA,5,Typ,0,NaN,Detchd,1935.0,Unf,2,480,Fa,TA,N,0,0,184,0,0,0,NaN,NaN,NaN,0,7,2007,WD
625,535105100,20,RL,NaN,9500,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,5,1963,1963,Gable,CompShg,Plywood,Plywood,BrkFace,247.0,TA,TA,CBlock,Gd,TA,No,BLQ,609,Unf,0,785,1394,GasA,Gd,Y,SBrkr,1394,0,0,1394,1,0,1,1,3,1,TA,6,Typ,2,Gd,Attchd,1963.0,RFn,2,514,TA,TA,Y,0,76,0,0,185,0,NaN,NaN,NaN,0,7,2009,WD

In [6]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 879 entries, 2658 to 1939
Data columns (total 79 columns):
PID                879 non-null int64
MS SubClass        879 non-null int64
MS Zoning          879 non-null object
Lot Frontage       719 non-null float64
Lot Area           879 non-null int64
Street             879 non-null object
Alley              58 non-null object
Lot Shape          879 non-null object
Land Contour       879 non-null object
Utilities          879 non-null object
Lot Config         879 non-null object
Land Slope         879 non-null object
Neighborhood       879 non-null object
Condition 1        879 non-null object
Condition 2        879 non-null object
Bldg Type          879 non-null object
House Style        879 non-null object
Overall Qual       879 non-null int64
Overall Cond       879 non-null int64
Year Built         879 non-null int64
Year Remod/Add     879 non-null int64
Roof Style         879 non-null object
Roof Matl          879 non-null object
Exterior 1st       879 non-null object
Exterior 2nd       879 non-null object
Mas Vnr Type       878 non-null object
Mas Vnr Area       878 non-null float64
Exter Qual         879 non-null object
Exter Cond         879 non-null object
Foundation         879 non-null object
Bsmt Qual          854 non-null object
Bsmt Cond          854 non-null object
Bsmt Exposure      854 non-null object
BsmtFin Type 1     854 non-null object
BsmtFin SF 1       879 non-null int64
BsmtFin Type 2     854 non-null object
BsmtFin SF 2       879 non-null int64
Bsmt Unf SF        879 non-null int64
Total Bsmt SF      879 non-null int64
Heating            879 non-null object
Heating QC         879 non-null object
Central Air        879 non-null object
Electrical         878 non-null object
1st Flr SF         879 non-null int64
2nd Flr SF         879 non-null int64
Low Qual Fin SF    879 non-null int64
Gr Liv Area        879 non-null int64
Bsmt Full Bath     879 non-null int64
Bsmt Half Bath     879 non-null int64
Full Bath          879 non-null int64
Half Bath          879 non-null int64
Bedroom AbvGr      879 non-null int64
Kitchen AbvGr      879 non-null int64
Kitchen Qual       879 non-null object
TotRms AbvGrd      879 non-null int64
Functional         879 non-null object
Fireplaces         879 non-null int64
Fireplace Qu       457 non-null object
Garage Type        835 non-null object
Garage Yr Blt      834 non-null float64
Garage Finish      834 non-null object
Garage Cars        879 non-null int64
Garage Area        879 non-null int64
Garage Qual        834 non-null object
Garage Cond        834 non-null object
Paved Drive        879 non-null object
Wood Deck SF       879 non-null int64
Open Porch SF      879 non-null int64
Enclosed Porch     879 non-null int64
3Ssn Porch         879 non-null int64
Screen Porch       879 non-null int64
Pool Area          879 non-null int64
Pool QC            4 non-null object
Fence              172 non-null object
Misc Feature       41 non-null object
Misc Val           879 non-null int64
Mo Sold            879 non-null int64
Yr Sold            879 non-null int64
Sale Type          879 non-null object
dtypes: float64(3), int64(34), object(42)
memory usage: 549.4+ KB

## Dropping features that were omitted from clean_X

In [7]:
test.columns

Index(['PID', 'MS SubClass', 'MS Zoning', 'Lot Frontage', 'Lot Area', 'Street',
       'Alley', 'Lot Shape', 'Land Contour', 'Utilities', 'Lot Config',
       'Land Slope', 'Neighborhood', 'Condition 1', 'Condition 2', 'Bldg Type',
       'House Style', 'Overall Qual', 'Overall Cond', 'Year Built',
       'Year Remod/Add', 'Roof Style', 'Roof Matl', 'Exterior 1st',
       'Exterior 2nd', 'Mas Vnr Type', 'Mas Vnr Area', 'Exter Qual',
       'Exter Cond', 'Foundation', 'Bsmt Qual', 'Bsmt Cond', 'Bsmt Exposure',
       'BsmtFin Type 1', 'BsmtFin SF 1', 'BsmtFin Type 2', 'BsmtFin SF 2',
       'Bsmt Unf SF', 'Total Bsmt SF', 'Heating', 'Heating QC', 'Central Air',
       'Electrical', '1st Flr SF', '2nd Flr SF', 'Low Qual Fin SF',
       'Gr Liv Area', 'Bsmt Full Bath', 'Bsmt Half Bath', 'Full Bath',
       'Half Bath', 'Bedroom AbvGr', 'Kitchen AbvGr', 'Kitchen Qual',
       'TotRms AbvGrd', 'Functional', 'Fireplaces', 'Fireplace Qu',
       'Garage Type', 'Garage Yr Blt', 'Garage Finish', 'Garage Cars',
       'Garage Area', 'Garage Qual', 'Garage Cond', 'Paved Drive',
       'Wood Deck SF', 'Open Porch SF', 'Enclosed Porch', '3Ssn Porch',
       'Screen Porch', 'Pool Area', 'Pool QC', 'Fence', 'Misc Feature',
       'Misc Val', 'Mo Sold', 'Yr Sold', 'Sale Type'],
      dtype='object')

In [8]:
test.columns = test.columns.str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '').str.replace('/', '_').str.replace('.', 'n')
test_col = [col for col in test.columns]
test_col

['pid',
 'ms_subclass',
 'ms_zoning',
 'lot_frontage',
 'lot_area',
 'street',
 'alley',
 'lot_shape',
 'land_contour',
 'utilities',
 'lot_config',
 'land_slope',
 'neighborhood',
 'condition_1',
 'condition_2',
 'bldg_type',
 'house_style',
 'overall_qual',
 'overall_cond',
 'year_built',
 'year_remod_add',
 'roof_style',
 'roof_matl',
 'exterior_1st',
 'exterior_2nd',
 'mas_vnr_type',
 'mas_vnr_area',
 'exter_qual',
 'exter_cond',
 'foundation',
 'bsmt_qual',
 'bsmt_cond',
 'bsmt_exposure',
 'bsmtfin_type_1',
 'bsmtfin_sf_1',
 'bsmtfin_type_2',
 'bsmtfin_sf_2',
 'bsmt_unf_sf',
 'total_bsmt_sf',
 'heating',
 'heating_qc',
 'central_air',
 'electrical',
 '1st_flr_sf',
 '2nd_flr_sf',
 'low_qual_fin_sf',
 'gr_liv_area',
 'bsmt_full_bath',
 'bsmt_half_bath',
 'full_bath',
 'half_bath',
 'bedroom_abvgr',
 'kitchen_abvgr',
 'kitchen_qual',
 'totrms_abvgrd',
 'functional',
 'fireplaces',
 'fireplace_qu',
 'garage_type',
 'garage_yr_blt',
 'garage_finish',
 'garage_cars',
 'garage_area',
 'garage_qual',
 'garage_cond',
 'paved_drive',
 'wood_deck_sf',
 'open_porch_sf',
 'enclosed_porch',
 '3ssn_porch',
 'screen_porch',
 'pool_area',
 'pool_qc',
 'fence',
 'misc_feature',
 'misc_val',
 'mo_sold',
 'yr_sold',
 'sale_type']

In [9]:
print(clean_train.shape)

train_col = [ col.lower() for col in clean_train.columns]
train_col

(1987, 30)

['gr_liv_area',
 'overall_qual',
 'neighborhood_nridght',
 'garage_cars',
 'exter_qual',
 'kitchen_qual',
 'neighborhood_stonebr',
 'bsmt_exposure',
 'bldg_type_1fam',
 'house_style_1story',
 'fireplace_qu',
 'mas_vnr_area',
 'bsmtfin_type_1',
 'neighborhood_noridge',
 'total_baths',
 'sale_type_new',
 'year_remod_add',
 'exterior_1st_brkface',
 'functional',
 'bldg_type_twnhse',
 'land_contour_bnk',
 'neighborhood_edwards',
 'mas_vnr_type_brkface',
 'neighborhood_crawfor',
 'full_bath',
 'roof_style_hip',
 'land_contour_hls',
 'bldg_type_twnhs',
 'garage_type_none',
 'bsmtfin_sf_1']

In [10]:
# we will use this list to track what are the columns that we don't have in the cleaned training set
not_in_train = []

In [11]:
for i in test_col:
    if i not in train_col: 
        not_in_train.append(i)
    else:
        continue

not_in_train

['pid',
 'ms_subclass',
 'ms_zoning',
 'lot_frontage',
 'lot_area',
 'street',
 'alley',
 'lot_shape',
 'land_contour',
 'utilities',
 'lot_config',
 'land_slope',
 'neighborhood',
 'condition_1',
 'condition_2',
 'bldg_type',
 'house_style',
 'overall_cond',
 'year_built',
 'roof_style',
 'roof_matl',
 'exterior_1st',
 'exterior_2nd',
 'mas_vnr_type',
 'exter_cond',
 'foundation',
 'bsmt_qual',
 'bsmt_cond',
 'bsmtfin_type_2',
 'bsmtfin_sf_2',
 'bsmt_unf_sf',
 'total_bsmt_sf',
 'heating',
 'heating_qc',
 'central_air',
 'electrical',
 '1st_flr_sf',
 '2nd_flr_sf',
 'low_qual_fin_sf',
 'bsmt_full_bath',
 'bsmt_half_bath',
 'half_bath',
 'bedroom_abvgr',
 'kitchen_abvgr',
 'totrms_abvgrd',
 'fireplaces',
 'garage_type',
 'garage_yr_blt',
 'garage_finish',
 'garage_area',
 'garage_qual',
 'garage_cond',
 'paved_drive',
 'wood_deck_sf',
 'open_porch_sf',
 'enclosed_porch',
 '3ssn_porch',
 'screen_porch',
 'pool_area',
 'pool_qc',
 'fence',
 'misc_feature',
 'misc_val',
 'mo_sold',
 'yr_sold',
 'sale_type']

We can't just drop the columns in not_in_train from the test dataframe - some of the discrepeancies might have arisen from using get_dummies() on the test data set so we'll need to look at those.

In [12]:
# keep_col will store the test column names that are substrings of columns in train.
# for instance we want to keep land_contour because it corresponds to land_contour_hls (a result of get_dummies) in train

keep_col = []

for col in not_in_train:
    count = 0
    for c in train_col:
        if col in c:
            # print(c)
            count = count + 1
            # print("count is:", count)
        else:
            pass
    if count > 0:
        keep_col.append(col)
    else:
        pass
    
keep_col

['land_contour',
 'neighborhood',
 'bldg_type',
 'house_style',
 'roof_style',
 'exterior_1st',
 'mas_vnr_type',
 'garage_type',
 'sale_type']

In [13]:
drop_cols = []

for k in not_in_train:
    if k not in keep_col: 
        drop_cols.append(k)
    else:
        continue
        
drop_cols

['pid',
 'ms_subclass',
 'ms_zoning',
 'lot_frontage',
 'lot_area',
 'street',
 'alley',
 'lot_shape',
 'utilities',
 'lot_config',
 'land_slope',
 'condition_1',
 'condition_2',
 'overall_cond',
 'year_built',
 'roof_matl',
 'exterior_2nd',
 'exter_cond',
 'foundation',
 'bsmt_qual',
 'bsmt_cond',
 'bsmtfin_type_2',
 'bsmtfin_sf_2',
 'bsmt_unf_sf',
 'total_bsmt_sf',
 'heating',
 'heating_qc',
 'central_air',
 'electrical',
 '1st_flr_sf',
 '2nd_flr_sf',
 'low_qual_fin_sf',
 'bsmt_full_bath',
 'bsmt_half_bath',
 'half_bath',
 'bedroom_abvgr',
 'kitchen_abvgr',
 'totrms_abvgrd',
 'fireplaces',
 'garage_yr_blt',
 'garage_finish',
 'garage_area',
 'garage_qual',
 'garage_cond',
 'paved_drive',
 'wood_deck_sf',
 'open_porch_sf',
 'enclosed_porch',
 '3ssn_porch',
 'screen_porch',
 'pool_area',
 'pool_qc',
 'fence',
 'misc_feature',
 'misc_val',
 'mo_sold',
 'yr_sold']

Even then, there are a couple of columns that are essential for feature-engineering to match our train data set so we want to omit these from drop-cols

* 'bsmt_full_bath' - for calculating 'full_bath' and 'total_baths'
* 'bsmt_half_bath' - for calculating 'total_baths'
* 'half_bath' - for calculating 'total_baths'

In [14]:
len(drop_cols)

57

In [15]:
drop_cols.remove('bsmt_full_bath')
drop_cols.remove('bsmt_half_bath')
drop_cols.remove('half_bath')

len(drop_cols)

54

In [16]:
# dropping the unnecessary columns
print(test.shape)
test.drop(columns=drop_cols, inplace=True )
print(test.shape)

(879, 79)
(879, 25)

## Checking for null rows and other irregularities

Checking what are the remaining null rows after dropping numerous columns

In [17]:
test.isnull().sum()

land_contour        0
neighborhood        0
bldg_type           0
house_style         0
overall_qual        0
year_remod_add      0
roof_style          0
exterior_1st        0
mas_vnr_type        1
mas_vnr_area        1
exter_qual          0
bsmt_exposure      25
bsmtfin_type_1     25
bsmtfin_sf_1        0
gr_liv_area         0
bsmt_full_bath      0
bsmt_half_bath      0
full_bath           0
half_bath           0
kitchen_qual        0
functional          0
fireplace_qu      422
garage_type        44
garage_cars         0
sale_type           0
dtype: int64

As with our approach for the train data set...

If a certain cell is NaN because the feature is not applicable, such as when "Mas Vnr Area" and "Mas Vnr Type" are NaN because there is no masonry veneer, we want to reflect that info by doing fillna() with 0 or "None". After all, this will affect the price predictions.

On the other hand, if data is missing/erroneous because of improper data entry/data collection, we will impute it, or drop it.

### masonry veneer

In [18]:
test.head(1)

,land_contour,neighborhood,bldg_type,house_style,overall_qual,year_remod_add,roof_style,exterior_1st,mas_vnr_type,mas_vnr_area,exter_qual,bsmt_exposure,bsmtfin_type_1,bsmtfin_sf_1,gr_liv_area,bsmt_full_bath,bsmt_half_bath,full_bath,half_bath,kitchen_qual,functional,fireplace_qu,garage_type,garage_cars,sale_type
Id,,,,,,,,,,,,,,,,,,,,,,,,,
2658,Lvl,OldTown,2fmCon,2Story,6,1950,Gable,AsbShng,None,0.0,TA,No,Unf,0,1928,0,0,2,0,Fa,Typ,NaN,Detchd,1,WD

In [19]:
print(test.loc[test["mas_vnr_type"].isnull(), "mas_vnr_type":].shape)
test.loc[test["mas_vnr_type"].isnull(), "mas_vnr_type":]

(1, 17)

,mas_vnr_type,mas_vnr_area,exter_qual,bsmt_exposure,bsmtfin_type_1,bsmtfin_sf_1,gr_liv_area,bsmt_full_bath,bsmt_half_bath,full_bath,half_bath,kitchen_qual,functional,fireplace_qu,garage_type,garage_cars,sale_type
Id,,,,,,,,,,,,,,,,,
868,NaN,NaN,Gd,No,Unf,0,1725,0,0,2,1,Gd,Typ,NaN,Attchd,2,WD

That row probably should have "None" for mas_vnr_type and 0 for mas_vnr_area so we'll use fillna

In [20]:
test["mas_vnr_type"] = test["mas_vnr_type"].fillna("None")
test["mas_vnr_type"].value_counts(dropna=False)

None       535
BrkFace    250
Stone       81
BrkCmn      12
CBlock       1
Name: mas_vnr_type, dtype: int64

In [21]:
test["mas_vnr_area"] = test["mas_vnr_area"].fillna(0)
test["mas_vnr_area"].value_counts(dropna=False).head()

0.0      533
216.0      7
80.0       5
196.0      5
420.0      5
Name: mas_vnr_area, dtype: int64

In [22]:
# checking if there are rows that have "None" for veneer type but area > 0
test[(test["mas_vnr_type"]=="None") & (test["mas_vnr_area"]!=0)]

,land_contour,neighborhood,bldg_type,house_style,overall_qual,year_remod_add,roof_style,exterior_1st,mas_vnr_type,mas_vnr_area,exter_qual,bsmt_exposure,bsmtfin_type_1,bsmtfin_sf_1,gr_liv_area,bsmt_full_bath,bsmt_half_bath,full_bath,half_bath,kitchen_qual,functional,fireplace_qu,garage_type,garage_cars,sale_type
Id,,,,,,,,,,,,,,,,,,,,,,,,,
442,Lvl,NridgHt,1Fam,1Story,9,2008,Hip,VinylSd,None,285.0,Ex,No,GLQ,1142,1808,1,0,2,0,Ex,Typ,Gd,Attchd,3,WD
404,Lvl,BrDale,TwnhsE,2Story,5,1970,Gable,HdBoard,None,312.0,TA,No,LwQ,765,1365,0,0,1,1,TA,Min1,NaN,Attchd,2,WD

In [23]:
# imputing with most frequent value that is not "None"
test.loc[442,"mas_vnr_type"] = "BrkFace"

# verifying
test.loc[442,"mas_vnr_type"]

'BrkFace'

In [24]:
# imputing with most frequent value that is not "None"
test.loc[404,"mas_vnr_type"] = "BrkFace"

# verifying
test.loc[404,"mas_vnr_type"]

'BrkFace'

In [25]:
# verifying
test[(test["mas_vnr_type"]=="None") & (test["mas_vnr_area"]!=0)]

Empty DataFrame
Columns: [land_contour, neighborhood, bldg_type, house_style, overall_qual, year_remod_add, roof_style, exterior_1st, mas_vnr_type, mas_vnr_area, exter_qual, bsmt_exposure, bsmtfin_type_1, bsmtfin_sf_1, gr_liv_area, bsmt_full_bath, bsmt_half_bath, full_bath, half_bath, kitchen_qual, functional, fireplace_qu, garage_type, garage_cars, sale_type]
Index: []

### basement

In [26]:
print(test.loc[test["bsmt_exposure"].isnull(), "bsmt_exposure":].shape)
test.loc[test["bsmt_exposure"].isnull(), "bsmt_exposure":]

(25, 14)

,bsmt_exposure,bsmtfin_type_1,bsmtfin_sf_1,gr_liv_area,bsmt_full_bath,bsmt_half_bath,full_bath,half_bath,kitchen_qual,functional,fireplace_qu,garage_type,garage_cars,sale_type
Id,,,,,,,,,,,,,,
2089,NaN,NaN,0,1340,0,0,1,0,TA,Typ,Gd,Attchd,1,WD
2071,NaN,NaN,0,998,0,0,1,0,TA,Min2,NaN,2Types,2,WD
971,NaN,NaN,0,1771,0,0,1,0,TA,Min1,TA,Attchd,2,WD
1887,NaN,NaN,0,882,0,0,1,0,TA,Typ,NaN,Attchd,1,WD
2005,NaN,NaN,0,1382,0,0,2,0,TA,Mod,TA,Attchd,1,WD
1507,NaN,NaN,0,1137,0,0,1,1,TA,Min1,NaN,NaN,0,WD
899,NaN,NaN,0,944,0,0,1,0,Fa,Min1,NaN,Detchd,2,WD
2623,NaN,NaN,0,1040,0,0,1,0,TA,Typ,NaN,Detchd,2,WD
1269,NaN,NaN,0,1048,0,0,1,0,TA,Min1,NaN,Detchd,2,WD
2488,NaN,NaN,0,1654,0,0,2,0,TA,Typ,NaN,Attchd,2,WD
1969,NaN,NaN,0,925,0,0,1,0,TA,Typ,NaN,Attchd,1,WD
291,NaN,NaN,0,2650,0,0,3,0,TA,Min2,NaN,NaN,0,WD
2680,NaN,NaN,0,912,0,0,1,0,TA,Typ,NaN,NaN,0,WD
1252,NaN,NaN,0,1764,0,0,2,1,TA,Maj2,TA,Attchd,1,WD
885,NaN,NaN,0,1126,0,0,2,0,Gd,Typ,NaN,Detchd,2,WD
795,NaN,NaN,0,845,0,0,1,0,TA,Typ,NaN,Detchd,1,WD
276,NaN,NaN,0,1664,0,0,2,0,TA,Typ,NaN,NaN,0,WD
1344,NaN,NaN,0,808,0,0,1,0,TA,Min2,NaN,Attchd,1,WD
2213,NaN,NaN,0,1226,0,0,1,1,TA,Min1,Gd,Attchd,2,WD
2185,NaN,NaN,0,1152,0,0,2,0,Fa,Typ,NaN,NaN,0,WD
808,NaN,NaN,0,1535,0,0,2,0,TA,Typ,NaN,Attchd,2,WD
1818,NaN,NaN,0,2020,0,0,2,0,TA,Typ,TA,Detchd,2,WD
1220,NaN,NaN,0,720,0,0,1,0,TA,Typ,NaN,Detchd,1,WD
552,NaN,NaN,0,1882,0,0,2,0,TA,Typ,TA,Attchd,2,WD
2617,NaN,NaN,0,1472,0,0,2,0,Gd,Typ,Gd,Attchd,2,WD

In [27]:
test["bsmt_exposure"].value_counts(dropna=False)

No     567
Av     130
Gd      81
Mn      76
NaN     25
Name: bsmt_exposure, dtype: int64

In [28]:
test["bsmt_exposure"] = test["bsmt_exposure"].fillna("None")
test["bsmt_exposure"].value_counts(dropna=False)

No      567
Av      130
Gd       81
Mn       76
None     25
Name: bsmt_exposure, dtype: int64

In [29]:
# We've also observed that null rows for bsmtfin_type_1 should be set to "None"

In [30]:
test["bsmtfin_type_1"] = test["bsmtfin_type_1"].fillna("None")
test["bsmtfin_type_1"].value_counts(dropna=False)

Unf     248
GLQ     244
ALQ     136
Rec     105
BLQ      69
LwQ      52
None     25
Name: bsmtfin_type_1, dtype: int64

### fireplace

In [31]:
print(test.loc[test["fireplace_qu"].isnull(), "fireplace_qu":].shape)
print(test["fireplace_qu"].value_counts(dropna=False))
test.loc[test["fireplace_qu"].isnull(), "fireplace_qu":]

(422, 4)
NaN    422
Gd     221
TA     193
Fa      16
Po      15
Ex      12
Name: fireplace_qu, dtype: int64

     fireplace_qu garage_type  garage_cars sale_type
Id
2658          NaN      Detchd            1       WD
2718          NaN      Attchd            2       WD
1989          NaN      Detchd            2       WD
333           NaN      Attchd            1       WD
1327          NaN      Detchd            1       WD
...           ...         ...          ...       ...
868           NaN      Attchd            2       WD
337           NaN      Attchd            2       WD
2765          NaN      Attchd            2       WD
2806          NaN      Attchd            2       WD
1672          NaN      Detchd            2       WD

[422 rows x 4 columns]

In [32]:
# assigning "None" to the null rows
test["fireplace_qu"] = test["fireplace_qu"].fillna("None")
test["fireplace_qu"].value_counts(dropna=False)

None    422
Gd      221
TA      193
Fa       16
Po       15
Ex       12
Name: fireplace_qu, dtype: int64

### garage type

In [33]:

print(test.loc[test["garage_type"].isnull(), "garage_type":].shape)
print(test["garage_type"].value_counts(dropna=False))
test.loc[test["garage_type"].isnull(), "garage_type":]

(44, 3)
Attchd     518
Detchd     246
BuiltIn     54
NaN         44
Basment      9
2Types       4
CarPort      4
Name: garage_type, dtype: int64

     garage_type  garage_cars sale_type
Id
1904         NaN            0       WD
979          NaN            0       WD
2362         NaN            0       WD
2188         NaN            0       WD
1988         NaN            0       WD
217          NaN            0       WD
2908         NaN            0       WD
1507         NaN            0       WD
1368         NaN            0     ConLD
332          NaN            0       WD
292          NaN            0       WD
760          NaN            0       COD
1408         NaN            0       WD
331          NaN            0       WD
171          NaN            0       WD
2304         NaN            0       Oth
1388         NaN            0       WD
291          NaN            0       WD
2680         NaN            0       WD
1943         NaN            0       WD
704          NaN            0       WD
758          NaN            0       WD
2232         NaN            0       WD
721          NaN            0       WD
2917         NaN            0       WD
212          NaN            0     ConLD
276          NaN            0       WD
663          NaN            0       WD
2919         NaN            0       WD
2043         NaN            0       WD
541          NaN            0       WD
2297         NaN            0       WD
1315         NaN            0       WD
1506         NaN            0       WD
743          NaN            0     ConLw
2185         NaN            0       WD
2473         NaN            0       New
2928         NaN            0       WD
1412         NaN            0       WD
713          NaN            0       New
2196         NaN            0       WD
214          NaN            0       WD
126          NaN            0       Oth
984          NaN            0       WD

In [34]:
# assigning "None" to the null rows
test["garage_type"] = test["garage_type"].fillna("None")
test["garage_type"].value_counts(dropna=False)

Attchd     518
Detchd     246
BuiltIn     54
None        44
Basment      9
2Types       4
CarPort      4
Name: garage_type, dtype: int64

## Encoding ordinal features

Checking each non-numeric column for its unique values and respective counts, 10 columns at a time.

Ordinal features will be mapped. We will also initialise a `drop_dummies` list to take note of the nominal features that need to be encoded using one-hot-encoding.

In [35]:
test_obj = test.select_dtypes(include=['object'])
test_obj.shape

(879, 15)

In [36]:
for x in range(0,10):
    print ("---- {} ---".format(test_obj.columns[x]))
    print("Null count:",test_obj.iloc[:,x].isnull().sum())
    print(test_obj.iloc[:,x].value_counts(dropna=False).sort_index(ascending=True))
    print()

---- land_contour ---
Null count: 0
Bnk     37
HLS     35
Low     17
Lvl    790
Name: land_contour, dtype: int64

---- neighborhood ---
Null count: 0
Blmngtn      6
Blueste      4
BrDale      11
BrkSide     32
ClearCr     17
CollgCr     87
Crawfor     32
Edwards     51
Gilbert     49
Greens       5
IDOTRR      24
MeadowV     13
Mitchel     32
NAmes      133
NPkVill      6
NWAmes      44
NoRidge     23
NridgHt     44
OldTown     76
SWISU       16
Sawyer      40
SawyerW     38
Somerst     52
StoneBr     13
Timber      24
Veenker      7
Name: neighborhood, dtype: int64

---- bldg_type ---
Null count: 0
1Fam      725
2fmCon     16
Duplex     34
Twnhs      32
TwnhsE     72
Name: bldg_type, dtype: int64

---- house_style ---
Null count: 0
1.5Fin     96
1.5Unf      7
1Story    422
2.5Fin      2
2.5Unf     10
2Story    275
SFoyer     33
SLvl       34
Name: house_style, dtype: int64

---- roof_style ---
Null count: 0
Flat         7
Gable      702
Gambrel     10
Hip        154
Mansard      4
Shed         2
Name: roof_style, dtype: int64

---- exterior_1st ---
Null count: 0
AsbShng     11
AsphShn      1
BrkComm      3
BrkFace     24
CemntBd     36
HdBoard    142
MetalSd    119
Plywood     69
PreCast      1
Stucco      16
VinylSd    302
Wd Sdng    144
WdShing     11
Name: exterior_1st, dtype: int64

---- mas_vnr_type ---
Null count: 0
BrkCmn      12
BrkFace    252
CBlock       1
None       533
Stone       81
Name: mas_vnr_type, dtype: int64

---- exter_qual ---
Null count: 0
Ex     26
Fa      9
Gd    292
TA    552
Name: exter_qual, dtype: int64

---- bsmt_exposure ---
Null count: 0
Av      130
Gd       81
Mn       76
No      567
None     25
Name: bsmt_exposure, dtype: int64

---- bsmtfin_type_1 ---
Null count: 0
ALQ     136
BLQ      69
GLQ     244
LwQ      52
None     25
Rec     105
Unf     248
Name: bsmtfin_type_1, dtype: int64

These features need to be encoded using get_dummies()

* land_contour
* bldg_type
* house_style
* roof_style
* exterior_1st
* mas_vnr_type
* neighborhood

However, neighborhood needs to be checked - we want to know which are the neighborhoods not in the data dictionary

These are ordinal and need to be mapped

* exter_qual
* bsmt_exposure
* bsmtfin_type_1

In [37]:
drop_dummies = []
drop_dummies.extend(["land_contour", "bldg_type", "house_style", "roof_style", "exterior_1st", "mas_vnr_type", "neighborhood"])

----

In [38]:
# datadict_hoods to store the list of expected neighbourhoods as provided in the data dictionary.

datadict_hoods = [
            "Blmngtn",
            "Blueste",
            "BrDale",
            "BrkSide",
            "ClearCr",
            "CollgCr",
            "Crawfor",
            "Edwards",
            "Gilbert",
            "IDOTRR",
            "MeadowV",
            "Mitchel",
            "Names",
            "NoRidge",
            "NPkVill",
            "NridgHt",
            "NWAmes",
            "OldTown",
            "SWISU",
            "Sawyer",
            "SawyerW",
            "Somerst",
            "StoneBr",
            "Timber",
            "Veenker"
    ]

datadict_hoods = [x.lower() for x in datadict_hoods]

datadict_hoods

['blmngtn',
 'blueste',
 'brdale',
 'brkside',
 'clearcr',
 'collgcr',
 'crawfor',
 'edwards',
 'gilbert',
 'idotrr',
 'meadowv',
 'mitchel',
 'names',
 'noridge',
 'npkvill',
 'nridght',
 'nwames',
 'oldtown',
 'swisu',
 'sawyer',
 'sawyerw',
 'somerst',
 'stonebr',
 'timber',
 'veenker']

In [39]:
test_hoods = {}
test_hoods = test["neighborhood"]
test_hoods = {x.lower() for x in test_hoods}

In [40]:
not_found = []
for i in test_hoods:
    if i not in datadict_hoods: 
        not_found.append(i)
    else:
        continue
        
not_found

['greens']

In [41]:
print(test[(test["neighborhood"].str.lower() == "greens")].shape)
test[(test["neighborhood"].str.lower() == "greens")]

(5, 25)

,land_contour,neighborhood,bldg_type,house_style,overall_qual,year_remod_add,roof_style,exterior_1st,mas_vnr_type,mas_vnr_area,exter_qual,bsmt_exposure,bsmtfin_type_1,bsmtfin_sf_1,gr_liv_area,bsmt_full_bath,bsmt_half_bath,full_bath,half_bath,kitchen_qual,functional,fireplace_qu,garage_type,garage_cars,sale_type
Id,,,,,,,,,,,,,,,,,,,,,,,,,
2519,Lvl,Greens,Twnhs,1Story,8,1980,Gable,Wd Sdng,None,0.0,Gd,Gd,GLQ,1009,1235,1,0,1,0,TA,Typ,TA,Attchd,2,WD
107,Lvl,Greens,TwnhsE,1Story,8,1980,Gable,Wd Sdng,None,0.0,Gd,Gd,GLQ,728,788,1,0,1,0,Gd,Typ,TA,Detchd,2,WD
576,Lvl,Greens,TwnhsE,1Story,8,1981,Gable,Wd Sdng,None,0.0,Gd,Gd,GLQ,960,1226,1,0,1,0,Gd,Typ,TA,Attchd,2,WD
2520,Lvl,Greens,Twnhs,1Story,8,1980,Gable,Wd Sdng,None,0.0,Gd,Gd,GLQ,860,1036,1,0,1,0,Gd,Typ,TA,Detchd,2,WD
1858,Lvl,Greens,TwnhsE,1Story,8,1998,Gable,Wd Sdng,None,0.0,Gd,Gd,GLQ,881,1295,1,0,1,0,Gd,Typ,TA,Attchd,2,WD

In [42]:
test.shape

(879, 25)

That's just 5 rows out of 879.

After one-hot-encoding, we will eventually trim down test to only the final set of features in train, so it's fine to leave this.

In [43]:
# initialising a mapper for "exter_qual"
qual_mapper = {"None": 0, "Po": 1, "Fa": 2, "TA":3, "Gd":4, "Ex": 5}

In [44]:
test["exter_qual"] = test["exter_qual"].replace(qual_mapper)
test["exter_qual"].value_counts(dropna=False)

3    552
4    292
5     26
2      9
Name: exter_qual, dtype: int64

In [45]:
# initialising a mapper for "bsmt_exposure"
bexp_mapper = {"None": 0, "No": 1, "Mn":2, "Av":3, "Gd": 4}

In [46]:
test["bsmt_exposure"] = test["bsmt_exposure"].replace(bexp_mapper)
test["bsmt_exposure"].value_counts(dropna=False)

1    567
3    130
4     81
2     76
0     25
Name: bsmt_exposure, dtype: int64

In [47]:
# initialising mapper for "bsmtfin_type_1"

bfin_mapper = {"None": 0, "Unf": 1, "LwQ": 2, "Rec":3, "BLQ": 4, "ALQ": 5, "GLQ":6}

In [48]:
test["bsmtfin_type_1"] = test["bsmtfin_type_1"].replace(bfin_mapper)
test["bsmtfin_type_1"].value_counts(dropna=False)

1    248
6    244
5    136
3    105
4     69
2     52
0     25
Name: bsmtfin_type_1, dtype: int64

In [49]:
for x in range(10,test_obj.shape[1]):
    print ("---- {} ---".format(test_obj.columns[x]))
    print("Null count:",test_obj.iloc[:,x].isnull().sum())
    print(test_obj.iloc[:,x].value_counts(dropna=False).sort_index(ascending=True))
    print()

---- kitchen_qual ---
Null count: 0
Ex     54
Fa     23
Gd    354
Po      1
TA    447
Name: kitchen_qual, dtype: int64

---- functional ---
Null count: 0
Maj1      7
Maj2      2
Min1     23
Min2     28
Mod       6
Typ     813
Name: functional, dtype: int64

---- fireplace_qu ---
Null count: 0
Ex       12
Fa       16
Gd      221
None    422
Po       15
TA      193
Name: fireplace_qu, dtype: int64

---- garage_type ---
Null count: 0
2Types       4
Attchd     518
Basment      9
BuiltIn     54
CarPort      4
Detchd     246
None        44
Name: garage_type, dtype: int64

---- sale_type ---
Null count: 0
COD       24
CWD        2
Con        1
ConLD      9
ConLI      2
ConLw      3
New       79
Oth        3
VWD        1
WD       755
Name: sale_type, dtype: int64

These features need to be encoded using get_dummies()
* garage_type
* sale_type

These are ordinal and need to be mapped using qual_mapper
* kitchen_qual
* fireplace_qu

functional is ordinal and needs to be mapped separately

In [50]:
drop_dummies.extend(["garage_type", "sale_type"])
drop_dummies

['land_contour',
 'bldg_type',
 'house_style',
 'roof_style',
 'exterior_1st',
 'mas_vnr_type',
 'neighborhood',
 'garage_type',
 'sale_type']

In [51]:
test["kitchen_qual"] = test["kitchen_qual"].replace(qual_mapper)
test["fireplace_qu"] = test["fireplace_qu"].replace(qual_mapper)

display(test["kitchen_qual"].value_counts(dropna=False))
display(test["fireplace_qu"].value_counts(dropna=False))

3    447
4    354
5     54
2     23
1      1
Name: kitchen_qual, dtype: int64

0    422
4    221
3    193
2     16
1     15
5     12
Name: fireplace_qu, dtype: int64

In [52]:
func_mapper = {"Sal": 0, "Sev": 1, "Maj2": 2, "Maj1":3, "Mod":4, "Min2": 5, "Min1":6, "Typ":7 }


test["functional"] = test["functional"].replace(func_mapper)

test["functional"].value_counts(dropna=False).sort_index()

2      2
3      7
4      6
5     28
6     23
7    813
Name: functional, dtype: int64

## Checking for outliers

In [53]:
test.describe()

,overall_qual,year_remod_add,mas_vnr_area,exter_qual,bsmt_exposure,bsmtfin_type_1,bsmtfin_sf_1,gr_liv_area,bsmt_full_bath,bsmt_half_bath,full_bath,half_bath,kitchen_qual,functional,fireplace_qu,garage_cars
count,879.000000,879.000000,879.000000,879.000000,879.000000,879.000000,879.000000,879.000000,879.000000,879.000000,879.000000,879.000000,879.000000,879.000000,879.000000,879.000000
mean,6.054608,1984.444824,106.861206,3.381115,1.630262,3.511945,443.397042,1500.531286,0.440273,0.055745,1.541524,0.399317,3.497156,6.846416,1.786121,1.744027
std,1.374756,20.454546,188.284115,0.562016,1.067663,2.093385,442.480223,517.413260,0.529983,0.229560,0.560908,0.506045,0.657654,0.613317,1.800971,0.751162
min,2.000000,1950.000000,0.000000,2.000000,0.000000,0.000000,0.000000,407.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2.000000,0.000000,0.000000
25%,5.000000,1967.000000,0.000000,3.000000,1.000000,1.000000,0.000000,1114.000000,0.000000,0.000000,1.000000,0.000000,3.000000,7.000000,0.000000,1.000000
50%,6.000000,1992.000000,0.000000,3.000000,1.000000,4.000000,374.000000,1436.000000,0.000000,0.000000,2.000000,0.000000,3.000000,7.000000,2.000000,2.000000
75%,7.000000,2003.000000,173.000000,4.000000,2.000000,6.000000,735.500000,1781.000000,1.000000,0.000000,2.000000,1.000000,4.000000,7.000000,4.000000,2.000000
max,10.000000,2010.000000,1378.000000,5.000000,4.000000,6.000000,2288.000000,4676.000000,2.000000,1.000000,4.000000,2.000000,5.000000,7.000000,5.000000,4.000000

## Feature engineering: aggregated features

In train, we also did some feature engineering to create total_baths and full_bath

In [54]:
test['full_bath'] = test['full_bath'] + test['bsmt_full_bath']
test['half_bath'] = test['half_bath'] + test['bsmt_half_bath']
test["total_baths"] = test["full_bath"] + test["half_bath"] 

test.describe()

,overall_qual,year_remod_add,mas_vnr_area,exter_qual,bsmt_exposure,bsmtfin_type_1,bsmtfin_sf_1,gr_liv_area,bsmt_full_bath,bsmt_half_bath,full_bath,half_bath,kitchen_qual,functional,fireplace_qu,garage_cars,total_baths
count,879.000000,879.000000,879.000000,879.000000,879.000000,879.000000,879.000000,879.000000,879.000000,879.000000,879.000000,879.000000,879.000000,879.000000,879.000000,879.000000,879.00000
mean,6.054608,1984.444824,106.861206,3.381115,1.630262,3.511945,443.397042,1500.531286,0.440273,0.055745,1.981797,0.455063,3.497156,6.846416,1.786121,1.744027,2.43686
std,1.374756,20.454546,188.284115,0.562016,1.067663,2.093385,442.480223,517.413260,0.529983,0.229560,0.752905,0.537834,0.657654,0.613317,1.800971,0.751162,0.94027
min,2.000000,1950.000000,0.000000,2.000000,0.000000,0.000000,0.000000,407.000000,0.000000,0.000000,1.000000,0.000000,1.000000,2.000000,0.000000,0.000000,1.00000
25%,5.000000,1967.000000,0.000000,3.000000,1.000000,1.000000,0.000000,1114.000000,0.000000,0.000000,1.000000,0.000000,3.000000,7.000000,0.000000,1.000000,2.00000
50%,6.000000,1992.000000,0.000000,3.000000,1.000000,4.000000,374.000000,1436.000000,0.000000,0.000000,2.000000,0.000000,3.000000,7.000000,2.000000,2.000000,2.00000
75%,7.000000,2003.000000,173.000000,4.000000,2.000000,6.000000,735.500000,1781.000000,1.000000,0.000000,2.000000,1.000000,4.000000,7.000000,4.000000,2.000000,3.00000
max,10.000000,2010.000000,1378.000000,5.000000,4.000000,6.000000,2288.000000,4676.000000,2.000000,1.000000,6.000000,2.000000,5.000000,7.000000,5.000000,4.000000,8.00000

Now to drop these columns that we'd saved initially

* 'bsmt_full_bath' 
* 'bsmt_half_bath'
* 'half_bath'

In [55]:
print(test.shape)
test.drop(columns=['bsmt_full_bath', 'bsmt_half_bath', 'half_bath'], inplace=True)
print(test.shape)

# print(test.shape)
# test.drop(columns=drop_cols, inplace=True )
# print(test.shape)

(879, 26)
(879, 23)

## Encoding nominal features

Now we want to run our get_dummies() on nominal features.

In [56]:
test.dtypes

land_contour       object
neighborhood       object
bldg_type          object
house_style        object
overall_qual        int64
year_remod_add      int64
roof_style         object
exterior_1st       object
mas_vnr_type       object
mas_vnr_area      float64
exter_qual          int64
bsmt_exposure       int64
bsmtfin_type_1      int64
bsmtfin_sf_1        int64
gr_liv_area         int64
full_bath           int64
kitchen_qual        int64
functional          int64
fireplace_qu        int64
garage_type        object
garage_cars         int64
sale_type          object
total_baths         int64
dtype: object

In [57]:
test.shape

(879, 23)

Our test set now has 23 features - i.e. before get_dummies() are run.

In [58]:

dummies = pd.get_dummies(test[drop_dummies])

print(dummies.shape)
dummies.head()

(879, 84)

,land_contour_Bnk,land_contour_HLS,land_contour_Low,land_contour_Lvl,bldg_type_1Fam,bldg_type_2fmCon,bldg_type_Duplex,bldg_type_Twnhs,bldg_type_TwnhsE,house_style_1.5Fin,house_style_1.5Unf,house_style_1Story,house_style_2.5Fin,house_style_2.5Unf,house_style_2Story,house_style_SFoyer,house_style_SLvl,roof_style_Flat,roof_style_Gable,roof_style_Gambrel,roof_style_Hip,roof_style_Mansard,roof_style_Shed,exterior_1st_AsbShng,exterior_1st_AsphShn,exterior_1st_BrkComm,exterior_1st_BrkFace,exterior_1st_CemntBd,exterior_1st_HdBoard,exterior_1st_MetalSd,exterior_1st_Plywood,exterior_1st_PreCast,exterior_1st_Stucco,exterior_1st_VinylSd,exterior_1st_Wd Sdng,exterior_1st_WdShing,mas_vnr_type_BrkCmn,mas_vnr_type_BrkFace,mas_vnr_type_CBlock,mas_vnr_type_None,mas_vnr_type_Stone,neighborhood_Blmngtn,neighborhood_Blueste,neighborhood_BrDale,neighborhood_BrkSide,neighborhood_ClearCr,neighborhood_CollgCr,neighborhood_Crawfor,neighborhood_Edwards,neighborhood_Gilbert,neighborhood_Greens,neighborhood_IDOTRR,neighborhood_MeadowV,neighborhood_Mitchel,neighborhood_NAmes,neighborhood_NPkVill,neighborhood_NWAmes,neighborhood_NoRidge,neighborhood_NridgHt,neighborhood_OldTown,neighborhood_SWISU,neighborhood_Sawyer,neighborhood_SawyerW,neighborhood_Somerst,neighborhood_StoneBr,neighborhood_Timber,neighborhood_Veenker,garage_type_2Types,garage_type_Attchd,garage_type_Basment,garage_type_BuiltIn,garage_type_CarPort,garage_type_Detchd,garage_type_None,sale_type_COD,sale_type_CWD,sale_type_Con,sale_type_ConLD,sale_type_ConLI,sale_type_ConLw,sale_type_New,sale_type_Oth,sale_type_VWD,sale_type_WD
Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2658,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1
2718,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2414,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1989,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1
625,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [59]:
test = pd.concat([test,dummies],axis=1)
test.head()

,land_contour,neighborhood,bldg_type,house_style,overall_qual,year_remod_add,roof_style,exterior_1st,mas_vnr_type,mas_vnr_area,exter_qual,bsmt_exposure,bsmtfin_type_1,bsmtfin_sf_1,gr_liv_area,full_bath,kitchen_qual,functional,fireplace_qu,garage_type,garage_cars,sale_type,total_baths,land_contour_Bnk,land_contour_HLS,land_contour_Low,land_contour_Lvl,bldg_type_1Fam,bldg_type_2fmCon,bldg_type_Duplex,bldg_type_Twnhs,bldg_type_TwnhsE,house_style_1.5Fin,house_style_1.5Unf,house_style_1Story,house_style_2.5Fin,house_style_2.5Unf,house_style_2Story,house_style_SFoyer,house_style_SLvl,roof_style_Flat,roof_style_Gable,roof_style_Gambrel,roof_style_Hip,roof_style_Mansard,roof_style_Shed,exterior_1st_AsbShng,exterior_1st_AsphShn,exterior_1st_BrkComm,exterior_1st_BrkFace,exterior_1st_CemntBd,exterior_1st_HdBoard,exterior_1st_MetalSd,exterior_1st_Plywood,exterior_1st_PreCast,exterior_1st_Stucco,exterior_1st_VinylSd,exterior_1st_Wd Sdng,exterior_1st_WdShing,mas_vnr_type_BrkCmn,mas_vnr_type_BrkFace,mas_vnr_type_CBlock,mas_vnr_type_None,mas_vnr_type_Stone,neighborhood_Blmngtn,neighborhood_Blueste,neighborhood_BrDale,neighborhood_BrkSide,neighborhood_ClearCr,neighborhood_CollgCr,neighborhood_Crawfor,neighborhood_Edwards,neighborhood_Gilbert,neighborhood_Greens,neighborhood_IDOTRR,neighborhood_MeadowV,neighborhood_Mitchel,neighborhood_NAmes,neighborhood_NPkVill,neighborhood_NWAmes,neighborhood_NoRidge,neighborhood_NridgHt,neighborhood_OldTown,neighborhood_SWISU,neighborhood_Sawyer,neighborhood_SawyerW,neighborhood_Somerst,neighborhood_StoneBr,neighborhood_Timber,neighborhood_Veenker,garage_type_2Types,garage_type_Attchd,garage_type_Basment,garage_type_BuiltIn,garage_type_CarPort,garage_type_Detchd,garage_type_None,sale_type_COD,sale_type_CWD,sale_type_Con,sale_type_ConLD,sale_type_ConLI,sale_type_ConLw,sale_type_New,sale_type_Oth,sale_type_VWD,sale_type_WD
Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2658,Lvl,OldTown,2fmCon,2Story,6,1950,Gable,AsbShng,None,0.0,3,1,1,0,1928,2,2,7,0,Detchd,1,WD,2,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1
2718,Lvl,Sawyer,Duplex,1Story,5,1977,Gable,Plywood,None,0.0,3,1,1,0,1967,2,3,7,0,Attchd,2,WD,2,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2414,Lvl,Gilbert,1Fam,2Story,7,2006,Gable,VinylSd,None,0.0,4,3,6,554,1496,3,4,7,4,Attchd,2,New,4,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1989,Lvl,OldTown,1Fam,1Story,5,2006,Gable,Wd Sdng,None,0.0,4,1,1,0,968,1,3,7,0,Detchd,2,WD,1,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1
625,Lvl,NAmes,1Fam,1Story,6,1963,Gable,Plywood,BrkFace,247.0,3,1,4,609,1394,2,3,7,4,Attchd,2,WD,3,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [60]:
test.shape

(879, 107)

In [61]:
# now to drop the redundant columns
test.drop(drop_dummies, axis = 1, inplace=True) 
print(test.shape)

(879, 98)

In [62]:
# now to check if everything is numerical 
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 879 entries, 2658 to 1939
Data columns (total 98 columns):
overall_qual            879 non-null int64
year_remod_add          879 non-null int64
mas_vnr_area            879 non-null float64
exter_qual              879 non-null int64
bsmt_exposure           879 non-null int64
bsmtfin_type_1          879 non-null int64
bsmtfin_sf_1            879 non-null int64
gr_liv_area             879 non-null int64
full_bath               879 non-null int64
kitchen_qual            879 non-null int64
functional              879 non-null int64
fireplace_qu            879 non-null int64
garage_cars             879 non-null int64
total_baths             879 non-null int64
land_contour_Bnk        879 non-null uint8
land_contour_HLS        879 non-null uint8
land_contour_Low        879 non-null uint8
land_contour_Lvl        879 non-null uint8
bldg_type_1Fam          879 non-null uint8
bldg_type_2fmCon        879 non-null uint8
bldg_type_Duplex        879 non-null uint8
bldg_type_Twnhs         879 non-null uint8
bldg_type_TwnhsE        879 non-null uint8
house_style_1.5Fin      879 non-null uint8
house_style_1.5Unf      879 non-null uint8
house_style_1Story      879 non-null uint8
house_style_2.5Fin      879 non-null uint8
house_style_2.5Unf      879 non-null uint8
house_style_2Story      879 non-null uint8
house_style_SFoyer      879 non-null uint8
house_style_SLvl        879 non-null uint8
roof_style_Flat         879 non-null uint8
roof_style_Gable        879 non-null uint8
roof_style_Gambrel      879 non-null uint8
roof_style_Hip          879 non-null uint8
roof_style_Mansard      879 non-null uint8
roof_style_Shed         879 non-null uint8
exterior_1st_AsbShng    879 non-null uint8
exterior_1st_AsphShn    879 non-null uint8
exterior_1st_BrkComm    879 non-null uint8
exterior_1st_BrkFace    879 non-null uint8
exterior_1st_CemntBd    879 non-null uint8
exterior_1st_HdBoard    879 non-null uint8
exterior_1st_MetalSd    879 non-null uint8
exterior_1st_Plywood    879 non-null uint8
exterior_1st_PreCast    879 non-null uint8
exterior_1st_Stucco     879 non-null uint8
exterior_1st_VinylSd    879 non-null uint8
exterior_1st_Wd Sdng    879 non-null uint8
exterior_1st_WdShing    879 non-null uint8
mas_vnr_type_BrkCmn     879 non-null uint8
mas_vnr_type_BrkFace    879 non-null uint8
mas_vnr_type_CBlock     879 non-null uint8
mas_vnr_type_None       879 non-null uint8
mas_vnr_type_Stone      879 non-null uint8
neighborhood_Blmngtn    879 non-null uint8
neighborhood_Blueste    879 non-null uint8
neighborhood_BrDale     879 non-null uint8
neighborhood_BrkSide    879 non-null uint8
neighborhood_ClearCr    879 non-null uint8
neighborhood_CollgCr    879 non-null uint8
neighborhood_Crawfor    879 non-null uint8
neighborhood_Edwards    879 non-null uint8
neighborhood_Gilbert    879 non-null uint8
neighborhood_Greens     879 non-null uint8
neighborhood_IDOTRR     879 non-null uint8
neighborhood_MeadowV    879 non-null uint8
neighborhood_Mitchel    879 non-null uint8
neighborhood_NAmes      879 non-null uint8
neighborhood_NPkVill    879 non-null uint8
neighborhood_NWAmes     879 non-null uint8
neighborhood_NoRidge    879 non-null uint8
neighborhood_NridgHt    879 non-null uint8
neighborhood_OldTown    879 non-null uint8
neighborhood_SWISU      879 non-null uint8
neighborhood_Sawyer     879 non-null uint8
neighborhood_SawyerW    879 non-null uint8
neighborhood_Somerst    879 non-null uint8
neighborhood_StoneBr    879 non-null uint8
neighborhood_Timber     879 non-null uint8
neighborhood_Veenker    879 non-null uint8
garage_type_2Types      879 non-null uint8
garage_type_Attchd      879 non-null uint8
garage_type_Basment     879 non-null uint8
garage_type_BuiltIn     879 non-null uint8
garage_type_CarPort     879 non-null uint8
garage_type_Detchd      879 non-null uint8
garage_type_None        879 non-null uint8
sale_type_COD           879 non-null uint8
sale_type_CWD           879 non-null uint8
sale_type_Con           879 non-null uint8
sale_type_ConLD         879 non-null uint8
sale_type_ConLI         879 non-null uint8
sale_type_ConLw         879 non-null uint8
sale_type_New           879 non-null uint8
sale_type_Oth           879 non-null uint8
sale_type_VWD           879 non-null uint8
sale_type_WD            879 non-null uint8
dtypes: float64(1), int64(13), uint8(84)
memory usage: 215.1 KB

Some of the categories have introduced uppercase letters and non-alphanumeric characters, so we'll need to strip this again.

In [63]:
test.columns = test.columns.str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '').str.replace('.', 'n')
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 879 entries, 2658 to 1939
Data columns (total 98 columns):
overall_qual            879 non-null int64
year_remod_add          879 non-null int64
mas_vnr_area            879 non-null float64
exter_qual              879 non-null int64
bsmt_exposure           879 non-null int64
bsmtfin_type_1          879 non-null int64
bsmtfin_sf_1            879 non-null int64
gr_liv_area             879 non-null int64
full_bath               879 non-null int64
kitchen_qual            879 non-null int64
functional              879 non-null int64
fireplace_qu            879 non-null int64
garage_cars             879 non-null int64
total_baths             879 non-null int64
land_contour_bnk        879 non-null uint8
land_contour_hls        879 non-null uint8
land_contour_low        879 non-null uint8
land_contour_lvl        879 non-null uint8
bldg_type_1fam          879 non-null uint8
bldg_type_2fmcon        879 non-null uint8
bldg_type_duplex        879 non-null uint8
bldg_type_twnhs         879 non-null uint8
bldg_type_twnhse        879 non-null uint8
house_style_1n5fin      879 non-null uint8
house_style_1n5unf      879 non-null uint8
house_style_1story      879 non-null uint8
house_style_2n5fin      879 non-null uint8
house_style_2n5unf      879 non-null uint8
house_style_2story      879 non-null uint8
house_style_sfoyer      879 non-null uint8
house_style_slvl        879 non-null uint8
roof_style_flat         879 non-null uint8
roof_style_gable        879 non-null uint8
roof_style_gambrel      879 non-null uint8
roof_style_hip          879 non-null uint8
roof_style_mansard      879 non-null uint8
roof_style_shed         879 non-null uint8
exterior_1st_asbshng    879 non-null uint8
exterior_1st_asphshn    879 non-null uint8
exterior_1st_brkcomm    879 non-null uint8
exterior_1st_brkface    879 non-null uint8
exterior_1st_cemntbd    879 non-null uint8
exterior_1st_hdboard    879 non-null uint8
exterior_1st_metalsd    879 non-null uint8
exterior_1st_plywood    879 non-null uint8
exterior_1st_precast    879 non-null uint8
exterior_1st_stucco     879 non-null uint8
exterior_1st_vinylsd    879 non-null uint8
exterior_1st_wd_sdng    879 non-null uint8
exterior_1st_wdshing    879 non-null uint8
mas_vnr_type_brkcmn     879 non-null uint8
mas_vnr_type_brkface    879 non-null uint8
mas_vnr_type_cblock     879 non-null uint8
mas_vnr_type_none       879 non-null uint8
mas_vnr_type_stone      879 non-null uint8
neighborhood_blmngtn    879 non-null uint8
neighborhood_blueste    879 non-null uint8
neighborhood_brdale     879 non-null uint8
neighborhood_brkside    879 non-null uint8
neighborhood_clearcr    879 non-null uint8
neighborhood_collgcr    879 non-null uint8
neighborhood_crawfor    879 non-null uint8
neighborhood_edwards    879 non-null uint8
neighborhood_gilbert    879 non-null uint8
neighborhood_greens     879 non-null uint8
neighborhood_idotrr     879 non-null uint8
neighborhood_meadowv    879 non-null uint8
neighborhood_mitchel    879 non-null uint8
neighborhood_names      879 non-null uint8
neighborhood_npkvill    879 non-null uint8
neighborhood_nwames     879 non-null uint8
neighborhood_noridge    879 non-null uint8
neighborhood_nridght    879 non-null uint8
neighborhood_oldtown    879 non-null uint8
neighborhood_swisu      879 non-null uint8
neighborhood_sawyer     879 non-null uint8
neighborhood_sawyerw    879 non-null uint8
neighborhood_somerst    879 non-null uint8
neighborhood_stonebr    879 non-null uint8
neighborhood_timber     879 non-null uint8
neighborhood_veenker    879 non-null uint8
garage_type_2types      879 non-null uint8
garage_type_attchd      879 non-null uint8
garage_type_basment     879 non-null uint8
garage_type_builtin     879 non-null uint8
garage_type_carport     879 non-null uint8
garage_type_detchd      879 non-null uint8
garage_type_none        879 non-null uint8
sale_type_cod           879 non-null uint8
sale_type_cwd           879 non-null uint8
sale_type_con           879 non-null uint8
sale_type_conld         879 non-null uint8
sale_type_conli         879 non-null uint8
sale_type_conlw         879 non-null uint8
sale_type_new           879 non-null uint8
sale_type_oth           879 non-null uint8
sale_type_vwd           879 non-null uint8
sale_type_wd_           879 non-null uint8
dtypes: float64(1), int64(13), uint8(84)
memory usage: 215.1 KB

## Trimming test into the same shape as clean_train

In [64]:
clean_train.head()

,gr_liv_area,overall_qual,neighborhood_nridght,garage_cars,exter_qual,kitchen_qual,neighborhood_stonebr,bsmt_exposure,bldg_type_1fam,house_style_1story,fireplace_qu,mas_vnr_area,bsmtfin_type_1,neighborhood_noridge,total_baths,sale_type_new,year_remod_add,exterior_1st_brkface,functional,bldg_type_twnhse,land_contour_bnk,neighborhood_edwards,mas_vnr_type_brkface,neighborhood_crawfor,full_bath,roof_style_hip,land_contour_hls,bldg_type_twnhs,garage_type_none,bsmtfin_sf_1
Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
109,1479,6,0,2.0,4,4,0,1,1,0,0,289.0,6,0,3.0,0,2005,0,7,0,0,0,1,0,2.0,0,0,0,0,533.0
544,2122,7,0,2.0,4,4,0,1,1,0,3,132.0,6,0,4.0,0,1997,0,7,0,0,0,1,0,3.0,0,0,0,0,637.0
153,1057,5,0,1.0,3,4,0,1,1,1,0,0.0,6,0,2.0,0,2007,0,7,0,0,0,0,0,2.0,0,0,0,0,731.0
318,1444,5,0,2.0,3,3,0,1,1,0,0,0.0,1,0,3.0,0,2007,0,7,0,0,0,0,0,2.0,0,0,0,0,0.0
255,1445,6,0,2.0,3,3,0,1,1,0,0,0.0,1,0,2.0,0,1993,0,7,0,0,0,0,0,2.0,0,0,0,0,0.0

In [65]:
# revisiting our columns in clean_train

train_col

['gr_liv_area',
 'overall_qual',
 'neighborhood_nridght',
 'garage_cars',
 'exter_qual',
 'kitchen_qual',
 'neighborhood_stonebr',
 'bsmt_exposure',
 'bldg_type_1fam',
 'house_style_1story',
 'fireplace_qu',
 'mas_vnr_area',
 'bsmtfin_type_1',
 'neighborhood_noridge',
 'total_baths',
 'sale_type_new',
 'year_remod_add',
 'exterior_1st_brkface',
 'functional',
 'bldg_type_twnhse',
 'land_contour_bnk',
 'neighborhood_edwards',
 'mas_vnr_type_brkface',
 'neighborhood_crawfor',
 'full_bath',
 'roof_style_hip',
 'land_contour_hls',
 'bldg_type_twnhs',
 'garage_type_none',
 'bsmtfin_sf_1']

In [66]:
clean_test = test[train_col]
print(clean_test.shape)
clean_test.head()

(879, 30)

,gr_liv_area,overall_qual,neighborhood_nridght,garage_cars,exter_qual,kitchen_qual,neighborhood_stonebr,bsmt_exposure,bldg_type_1fam,house_style_1story,fireplace_qu,mas_vnr_area,bsmtfin_type_1,neighborhood_noridge,total_baths,sale_type_new,year_remod_add,exterior_1st_brkface,functional,bldg_type_twnhse,land_contour_bnk,neighborhood_edwards,mas_vnr_type_brkface,neighborhood_crawfor,full_bath,roof_style_hip,land_contour_hls,bldg_type_twnhs,garage_type_none,bsmtfin_sf_1
Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2658,1928,6,0,1,3,2,0,1,0,0,0,0.0,1,0,2,0,1950,0,7,0,0,0,0,0,2,0,0,0,0,0
2718,1967,5,0,2,3,3,0,1,0,1,0,0.0,1,0,2,0,1977,0,7,0,0,0,0,0,2,0,0,0,0,0
2414,1496,7,0,2,4,4,0,3,1,0,4,0.0,6,0,4,1,2006,0,7,0,0,0,0,0,3,0,0,0,0,554
1989,968,5,0,2,4,3,0,1,1,1,0,0.0,1,0,1,0,2006,0,7,0,0,0,0,0,1,0,0,0,0,0
625,1394,6,0,2,3,3,0,1,1,1,4,247.0,4,0,3,0,1963,0,7,0,0,0,1,0,2,0,0,0,0,609

# Modeling and predicting

In [67]:
# initialising our training set for modeling
X_train = clean_train
X_train.shape

(1987, 30)

In [68]:
# initialising our test set for predicting
X_test = clean_test
X_test.shape

(879, 30)

In [69]:
y_train = pd.read_csv('./datasets/clean_y.csv', index_col = 'Id')
print(y_train.shape)
y_train.head()

(1987, 1)

     saleprice
Id
109     130500
544     220000
153     109000
318     174000
255     138500

In [70]:
# scaling

ss = StandardScaler()

X_train_sc = ss.fit_transform(X_train)
X_test_sc = ss.transform(X_test)

In [71]:
# initialising lasso regression with the optimal alpha derived in the previous notebook

opt_alpha = 398.26111565359196
lasso = Lasso(alpha=opt_alpha)

lasso.fit(X_train_sc, y_train)

Lasso(alpha=398.26111565359196, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [72]:
test_pred = lasso.predict(X_test_sc)
test_pred

array([120766.51089719, 146783.696766  , 240476.79438353, 129448.26515661,
       173758.44650828,  68290.7653169 , 102402.94999103, 152192.8769469 ,
       164901.93533733, 165421.61605506, 148692.65872227, 130463.0831068 ,
       152388.6025081 , 280411.72286181, 141479.93295529, 124016.90673254,
       137648.78971847, 116859.33630647, 186610.78759214, 210598.29710079,
       145776.51246599, 127188.56096794, 171636.7971585 , 161519.26932237,
       175321.89730215, 126829.80217031, 136607.17191818, 147531.7952204 ,
       166432.51102361,  50138.11360792,  95187.0951185 , 104257.80481652,
       257166.29047146, 161270.37834569, 212622.48487916, 183719.01734822,
       113641.24067637,  73730.69521191, 147842.08527795, 184133.68691286,
       164542.93670768, 206812.34717047, 156750.87906207, 163776.12978434,
       209861.05754404,  86608.76336374, 229105.7668389 , 118259.92043138,
       119432.32878506, 127846.68197492, 104472.54610991, 231981.13549387,
       244713.86653745, 125324.21328269, 108314.11772277, 159798.2771455 ,
       167818.14146793, 147555.83304647, 170895.18115318, 237833.12488061,
       322533.87031919, 142730.44580284, 148587.82502425, 169381.61820628,
       184740.95023255, 322252.18102265,  92348.54692106, 234141.26060459,
        72211.18739162, 164902.4187619 ,  95275.36920408, 348466.35220992,
       192625.39898692, 185828.14132603, 127945.881799  , 196597.12088707,
       480024.9112466 , 153801.59217851, 145446.29200552,  88291.90052026,
       372092.49279342, 197015.85916609, 132224.29791198, 141597.9033403 ,
       113770.81055414, 217318.84317204, 335916.66406958, 139789.63854135,
       193331.96780279, 228157.77851384, 142493.81515591, 135914.28127326,
        91572.1046369 , 110156.08332768, 259965.7582565 , 122085.41062185,
       148011.59682984, 170416.48010286, 248373.52665072, 199030.44257762,
       221742.71678038, 293452.62161524, 180005.0554995 , 121302.79572442,
       436884.22891301, 145100.78270643, 116303.17937556, 176933.56060103,
       198354.19427777, 175181.53012345, 127856.04478389, 191267.59696615,
       217534.46210833,  98782.31025057, 111742.67545253, 241033.03372432,
       449090.49661607, 143705.59522675, 105057.32440405, 316484.24624258,
       184253.79291723, 362694.20401745, 326723.94492999, 320366.83370075,
       172775.74605209, 139048.34924544, 356252.99139175, 116858.06822737,
       136019.49679875, 129644.54576506, 251136.75179901, 141756.28187521,
       206404.63206497, 138114.935816  , 178260.92908263, 156052.70268589,
       225089.15987057, 200348.20832225, 170419.3531107 , 247419.79115805,
       115766.81650768, 195311.04143681, 148861.13865255, 128211.94273595,
       161264.24011603,  83944.30684899, 143710.92833012, 152290.31812653,
       136618.01219209,  54418.62697595, 224887.34395249, 193464.76794415,
       143461.64672341, 101316.33300455, 123029.35686465, 120165.80384798,
       132900.10028238,  58852.82862767, 146051.15176009, 245941.92897045,
       241410.98611343, 219815.2719707 , 106393.65349435, 123627.23186935,
       439372.96714092, 270068.52905997, 234254.26878031, 166545.71554761,
       166830.34728994, 266017.0836996 , 204433.52267781, 463070.27724665,
       137360.67815629, 162038.01738903, 148639.47365103, 206726.43507953,
       166532.56934886, 105135.72319741, 151942.44287684,  67629.6187267 ,
       160519.81456623, 131540.67542816, 202347.475023  , 251967.73971549,
       198347.93486353, 162748.44842574, 116555.50919514, 212574.86492475,
       185766.15257712, 127952.7357108 ,  59439.85037444, 182511.23347738,
       126679.7317046 , 121589.92600413, 112884.13385582, 196346.58174671,
       153174.84764008, 294967.13754806, 132347.57356302, 118149.05492939,
       107091.62386106, 290830.98691187, 186862.50077698, 127932.47759779,
       190975.14634942, 124963.40271868, 115247.72720786, 136783.47726588,
       139518.39979942, 238356.69090405, 220853.63775034, 188933.05833042,
       210946.59262023, 114954.5976813 , 276235.81599759, 244727.20304608,
       206778.46344441, 211155.65798609, 157253.6131777 , 109823.35664056,
       167493.1107743 , 181205.68080685, 123462.04171695, 187400.06762623,
       198067.22104516, 137084.63044264, 113493.17851742, 244948.55933872,
       215893.9933171 , 146918.92520601, 288220.68105342, 163741.92875852,
        58646.51370735, 154689.8829833 ,  86959.34519616, 298288.20328707,
       169163.92718015,  93360.40920316, 400977.95718577, 306476.11650693,
       181917.85418901, 250503.98193691, 170844.76276185, 314326.30606834,
       224683.46389997, 312311.75755183, 264749.74965136, 114567.80733424,
       118758.43408875, 169002.57684018, 299166.07825268, 298308.18331905,
       136580.87175781, 235421.68491978, 219058.0607988 , 199488.71940458,
        98742.62122992,  82402.17000011, 408932.30502628, 224587.48252662,
       249087.23939203, 203950.87888977, 133922.24178678, 105342.93405425,
       154933.99850089, 240182.6964954 , 159640.93224972, 133078.55708757,
       218562.21715153, 175476.25242484, 142535.87480613, 201848.80312168,
       202047.95881797, 182237.3979596 , 333828.84361556, 116700.28080606,
       140960.37462049, 151534.98180311, 182351.04190121, 107760.22815488,
       110994.68583901, 237443.32903373, 125528.70234039, 115162.86969003,
        98659.41100325, 142604.06043679, 249940.20060428, 211705.99462867,
        97941.27496237, 101591.3317477 , 132283.15587429, 106151.4830223 ,
       124893.7889771 ,  67183.81822395, 112092.58586195, 146037.24646535,
       158252.8749323 , 211530.51075788, 270179.71429713, 250820.04260527,
       176788.40879332, 179961.72652111, 320287.12971109, 123977.7872172 ,
       150444.74933815,  85784.16967738, 108311.19920333, 195490.5735026 ,
       219302.2987652 , 134583.35956757, 116122.44073226, 208038.0067072 ,
       246986.09343003, 238322.34702864, 283607.4023242 , 130961.14567327,
       380022.90646019, 391439.33884745, 288065.19382283, 228822.92740999,
       117165.55781803,  62734.84397744, 111433.06563516, 170446.33152228,
       277194.6309374 , 138987.98936414, 114119.16414364, 153767.44743222,
       187952.27433572, 186108.19771158, 134235.14686846, 158992.14509905,
       188118.58138275, 148924.56653301, 196723.06250555, 106995.7133089 ,
       177813.2080037 , 101904.74190498, 125956.89079528, 132938.40970709,
       180312.33992919, 185836.99178271, 105418.9591008 , 138102.55469788,
       180247.0786711 , 298450.83973903, 235196.66502705, 170463.46145035,
       101970.93355328, 226821.70739095, 163440.9504315 , 143583.1865125 ,
       168982.19547887, 108349.57246737, 281829.84647505, 131888.7303789 ,
       262598.65529999, 162459.92663123, 220070.2061337 , 245919.57846659,
       115443.79854977, 138593.91355967, 134105.36447039,  73455.88538054,
       152323.11444972, 204025.42961886, 283908.75674399, 207934.3405937 ,
       208413.92762301, 206254.07070841, 109981.35080306, 201263.50305941,
        96466.63951728, 156520.52881261, 379109.91543752, 129414.91107461,
       296739.74165087, 184674.97716976, 275024.40575366, 236502.84901868,
       128414.31414409, 155955.86201336, 128407.39697545, 341937.97330537,
       333319.97573557, 227383.99057567, 188500.22450547, 162741.74988832,
       219799.75183801, 119590.6363498 , 123246.98368295,  91856.58583735,
       291926.52067117, 158475.11103577, 113762.97801061, 179718.92135728,
        86657.66325294, 196820.58909832, 202492.5377586 , 139398.83460391,
        84444.42909293, 205790.87654802, 230845.3670177 , 131351.10879396,
       291831.90620374, 145759.66216485, 137344.73342359, 149573.57355557,
       226050.69813328, 307787.95626891, 136119.08070586, 124148.03765261,
       149735.49099404, 242683.25030244, 130502.96352909, 257681.79812022,
       341060.06313371, 117801.40693412, 217628.09741448, 107871.97381767,
       167641.40179602, 236024.93589216, 106906.2190356 , 235943.10331174,
       124716.57133481, 210417.17218993, 383445.70466117, 201641.90280419,
       215080.28298653, 134712.06336491, 286463.32069757, 116079.58993137,
       136931.29502444, 124765.4776855 , 203683.6525186 ,  92903.16369202,
       335323.98746316, 225247.77409241, 166726.49352087, 138312.41172927,
       146592.71832777, 202230.88945866, 135999.3069787 , 113286.37887608,
       176427.63605862, 162249.60448789, 210286.35638999,  45848.19857752,
       100164.34185677, 303084.07620748, 150522.79016457, 226973.31343595,
       276729.6967476 , 253953.1197876 , 188284.76250783, 201034.85702092,
       226718.3462341 , 232374.19873122, 116072.4729267 , 245977.19967336,
       115103.07472102, 144799.53910734, 126727.04934442, 149159.20150025,
       488937.57901961, 125643.21498699, 226571.46246467, 244489.90628958,
       221495.44619747,  97455.04719309, 127794.55110583, 142484.03939216,
       245508.03594069, 188013.67632687, 108386.90099252, 253948.87761137,
       211473.96909487, 105060.86291995, 148095.69177023, 100760.45711205,
       203968.60148992,  68905.67720306, 214808.06855231, 100893.02512991,
       191249.48144323, 317260.4771249 , 146330.22274676, 167463.30187257,
       193816.03165809, 177839.51630343, 142867.42787916, 152343.35595809,
       212519.15071987, 174171.17328991, 224788.63921029, 377895.52997967,
       170611.84627547,  92365.74336614, 124190.11780711, 181807.78049351,
       107393.94267495, 181420.49266526, 235623.54735719, 204869.49791229,
       148399.23616148, 253625.57136144, 131393.41015349, 275360.73704257,
        98066.08282729,  97394.30950194, 248448.72301276, 118726.41710653,
       113276.0989751 , 127266.78539709, 149450.34168265,  41324.09215153,
       189093.39046165, 159493.47490657, 193846.63652804, 271720.76034452,
       280882.55269099, 107889.91547926, 127503.66987025, 125514.45004189,
       121289.85318851, 223488.58271938, 412119.43457317, 196010.13501669,
       108805.30344057, 133161.04323595,  51899.98266442, 106323.97471244,
       226030.33311489, 150904.43291908, 189695.1089917 , 171583.6146439 ,
       127016.97048056,  62559.47809342, 229191.01191283, 133254.15208547,
       159128.49426363, 147681.24093344,  86527.86117776,  71046.50323603,
       116355.70859821, 238980.6328043 , 340197.26386526, 241348.07110955,
       117578.37498837,  90096.75472606, 309242.34598886, 138164.39806419,
       297875.3844391 ,  83573.34136513, 183288.77863736, 218928.34873804,
        76217.81127843,  96332.85600053, 139037.37611386, 116303.33175705,
       174688.55808507, 109356.49597991, 146443.67975182, 181656.69807027,
       130032.70207259, 120562.65513233, 133222.61180585, 123118.48753278,
       198387.23426211, 123020.12074857, 157639.34388964, 150525.21119107,
       126064.2157743 ,  92420.27576577, 141419.0641379 , 173045.73254313,
       128163.61752758, 184611.88337952, 151694.38136645, 205721.92685924,
       118877.08083185, 153660.81608396, 153690.35774864, 291009.08109289,
       116281.39350222, 148770.35993857, 166877.87152454, 150332.23361182,
       122523.07181521, 281417.46225404, 221267.05938169, 135019.22690118,
       111139.56991679, 134106.36588796, 130439.91624465, 324480.62686802,
       218807.07803812, 142035.8168538 , 133088.38039555,  93546.80511505,
       382711.15291099, 124025.78866623, 199589.61034817, 121706.70010534,
       185316.54096408, 240090.79342155,  94243.89510714, 130985.2135805 ,
       118123.79989469, 165519.70086044, 120850.27813687, 112822.78652758,
       349141.36335816, 228313.16435395, 145589.4379848 , 141262.99991963,
        22668.69763538, 220263.02951105, 281889.10598372,  61300.50219164,
       176515.54897144, 216019.19680594, 108105.88832165, 146206.07132424,
       107114.48176947, 152924.57420795, 152401.06429361, 197803.94947232,
       120767.53462587, 326457.98555914, 149722.51862184, 181820.1586286 ,
       188972.30166452, 131331.87841765,  77954.15415241, 146894.41540446,
       190894.88323263, 135974.9606283 , 161666.31047624, 136512.98319781,
       151172.00223127, 311177.70358294, 137842.00604318, 214460.7099935 ,
       267924.06044841, 150913.86811296,  64232.23534077, 233217.8538633 ,
       181014.30844215, 127007.78146236, 166496.96635308, 153339.60140615,
       116607.30519986, 100622.87566641, 149349.57225061,  64290.47495811,
       159601.88336208, 211746.10869835, 162179.18082243, 278406.29923725,
       179176.36563193, 161549.93004765, 164425.49439795, 173376.01907941,
       229022.95164912, 386741.02668513, 226049.68191975, 203133.65659937,
       179891.71244046, 158532.99564094, 268131.52853548, 219463.38349906,
       233889.02382886, 250814.15008086, 142866.34316208, 118469.13507113,
       138526.11440816, 133105.31739704,  70314.77504368, 141871.17544431,
       106865.49427986, 342362.08462448, 203004.90708975, 165292.26239858,
       231129.13010193, 195855.18779869, 158882.91372448, 208046.41039944,
       400920.58179156, 168991.78032847, 166632.41325296,  70497.9115224 ,
       120367.39825888, 298357.28652975, 130612.70748799, 222053.35753489,
       163239.60075261, 219518.16649751, 358940.50821632,  94065.74616698,
       251557.77938611, 161736.70963493, 144418.56281613, 142419.36795178,
       104283.06273874, 282876.51739922, 281945.55120617, 156028.68578201,
       129261.27162063,  98696.46220152, 318536.00310498, 214654.87570253,
       107468.95056864, 135166.92762249, 126746.5594552 , 127910.78726934,
       190529.20026159, 288713.45737477, 209915.08654721, 191359.69712488,
       246817.2314709 , 220813.97733371, 248052.19672186, 139138.08453042,
       105402.20660284, 312212.03109747, 197114.82466307, 190549.56766154,
       139270.00200695, 283116.76641321,  87197.05328458, 240294.51527294,
       183748.58058795, 248594.68082894, 138718.94576921, 195046.95810432,
       147915.7340124 , 141901.25940437, 155465.96710348, 145762.23979062,
       126601.56885012, 225411.20799825, 183780.7579659 , 156760.64637195,
       106612.95933797, 185009.81682028, 170440.46568732, 187027.51323047,
       217415.8036603 , 113949.4893216 , 315059.87852444, 234827.16106399,
       138248.54458354, 139053.60726278, 168068.2713431 , 151937.98255761,
       115846.99943274, 424754.39525522,  88657.47307347, 151582.29040601,
       247102.45587648, 141255.05842405, 215828.94071241, 132682.66759225,
       235418.21867009, 149110.19172729, 301401.0533972 , 182278.63455647,
       211624.06389369, 302293.40100275, 158266.08278586, 268878.90944973,
       180584.91553545, 133568.72254467, 234273.88983257, 129425.96269878,
       129789.94060724, 238993.98129404, 138763.59918202, 103549.85816755,
       171315.87996635, 173444.78773382, 406561.88292004, 104495.94102711,
       117611.2699628 , 108796.26822374, 154092.37346913, 264749.74965136,
       111742.22013366, 242222.13253489, 165972.59727672, 197630.9083563 ,
       238870.92816397, 198823.61889019, 298953.06743016, 155895.49537034,
       206775.74433611, 151883.82026933, 253775.00894274, 239094.36221182,
       231287.0808344 , 147591.78278058, 114769.33123718, 166634.35745517,
       120993.9235762 , 253050.89582844, 104302.39722539, 131267.91998772,
       191116.278983  , 140763.96630916, 122502.72515669, 139443.65105636,
       332743.64884008, 178510.00800953, 163687.2124868 , 249368.82008457,
       200641.13311121, 216872.47733752,  98608.15455757, 111599.55700896,
       151253.51918708, 167361.16248755, 102670.29331118, 356355.97360144,
       121543.53297961, 177680.71854082, 212992.5748911 , 337192.69724625,
       138970.26527357, 177620.73725876, 150753.10969813, 162573.7236746 ,
       148227.14586432, 278439.48936591, 233964.32318432, 152150.45027183,
       127300.23871995, 350663.95470482, 146037.20614886, 138211.00160337,
       123486.30558342, 208686.48754287, 218021.74935487, 236313.13542198,
       128970.88358897, 173287.56561227, 163748.22131007, 251329.43453315,
       232393.30809064, 101083.90981842, 173608.74212921, 152335.66356995,
       182915.36296696, 132933.084251  , 133269.23998015, 157412.97456344,
       112370.59871641, 263805.30213646,  89203.98087598, 190031.52849057,
       113412.01432813, 349571.32062724, 116071.39366378, 104783.13047282,
       169737.08136499, 158832.55170671, 193363.44531264, 177635.07922313,
       260535.08768396, 179752.61263956, 188712.12766888, 257564.35680198,
       342494.89262208, 209165.82995769, 192417.67935942, 218864.50109926,
       132339.98245178, 108615.82544288, 122958.69825727])

In [73]:
test["SalePrice"] = test_pred
test.head()

,overall_qual,year_remod_add,mas_vnr_area,exter_qual,bsmt_exposure,bsmtfin_type_1,bsmtfin_sf_1,gr_liv_area,full_bath,kitchen_qual,functional,fireplace_qu,garage_cars,total_baths,land_contour_bnk,land_contour_hls,land_contour_low,land_contour_lvl,bldg_type_1fam,bldg_type_2fmcon,bldg_type_duplex,bldg_type_twnhs,bldg_type_twnhse,house_style_1n5fin,house_style_1n5unf,house_style_1story,house_style_2n5fin,house_style_2n5unf,house_style_2story,house_style_sfoyer,house_style_slvl,roof_style_flat,roof_style_gable,roof_style_gambrel,roof_style_hip,roof_style_mansard,roof_style_shed,exterior_1st_asbshng,exterior_1st_asphshn,exterior_1st_brkcomm,exterior_1st_brkface,exterior_1st_cemntbd,exterior_1st_hdboard,exterior_1st_metalsd,exterior_1st_plywood,exterior_1st_precast,exterior_1st_stucco,exterior_1st_vinylsd,exterior_1st_wd_sdng,exterior_1st_wdshing,mas_vnr_type_brkcmn,mas_vnr_type_brkface,mas_vnr_type_cblock,mas_vnr_type_none,mas_vnr_type_stone,neighborhood_blmngtn,neighborhood_blueste,neighborhood_brdale,neighborhood_brkside,neighborhood_clearcr,neighborhood_collgcr,neighborhood_crawfor,neighborhood_edwards,neighborhood_gilbert,neighborhood_greens,neighborhood_idotrr,neighborhood_meadowv,neighborhood_mitchel,neighborhood_names,neighborhood_npkvill,neighborhood_nwames,neighborhood_noridge,neighborhood_nridght,neighborhood_oldtown,neighborhood_swisu,neighborhood_sawyer,neighborhood_sawyerw,neighborhood_somerst,neighborhood_stonebr,neighborhood_timber,neighborhood_veenker,garage_type_2types,garage_type_attchd,garage_type_basment,garage_type_builtin,garage_type_carport,garage_type_detchd,garage_type_none,sale_type_cod,sale_type_cwd,sale_type_con,sale_type_conld,sale_type_conli,sale_type_conlw,sale_type_new,sale_type_oth,sale_type_vwd,sale_type_wd_,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2658,6,1950,0.0,3,1,1,0,1928,2,2,7,0,1,2,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,120766.510897
2718,5,1977,0.0,3,1,1,0,1967,2,3,7,0,2,2,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,146783.696766
2414,7,2006,0.0,4,3,6,554,1496,3,4,7,4,2,4,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,240476.794384
1989,5,2006,0.0,4,1,1,0,968,1,3,7,0,2,1,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,129448.265157
625,6,1963,247.0,3,1,4,609,1394,2,3,7,4,2,3,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,173758.446508

In [74]:
submission = test[["SalePrice"]]
submission.head()

          SalePrice
Id
2658  120766.510897
2718  146783.696766
2414  240476.794384
1989  129448.265157
625   173758.446508

In [75]:
submission.to_csv("./datasets/submission_1.csv", index=True)

In [77]:
lr = LinearRegression()

In [79]:
lr.fit(X_train_sc, y_train)
lr_pred = lr.predict(X_test_sc)
lr_pred

array([[119277.68874618],
       [147413.31399015],
       [241741.87704404],
       [129813.96326208],
       [173653.00339214],
       [ 65279.90429209],
       [102518.63766042],
       [153467.04653555],
       [161788.78913501],
       [166868.7436256 ],
       [147266.95197549],
       [130762.84711956],
       [152826.51812614],
       [281781.77723163],
       [138231.6213884 ],
       [120850.97207848],
       [137204.776058  ],
       [115653.21942813],
       [184164.67374551],
       [210319.634599  ],
       [146254.06543392],
       [128237.61191818],
       [169513.80612252],
       [161412.14358756],
       [175703.06598144],
       [127744.72030609],
       [135986.31918633],
       [145884.11445174],
       [164688.79828581],
       [ 52070.583524  ],
       [ 95716.897635  ],
       [104062.96307163],
       [258098.26472078],
       [162774.64358514],
       [212560.23426247],
       [183452.63779954],
       [112765.86921039],
       [ 72757.24123936],
       [148178.83956683],
       [184019.01039432],
       [162638.29995671],
       [206308.95248594],
       [157498.14859799],
       [164036.83380665],
       [207348.69487049],
       [ 87237.45605967],
       [228167.58847325],
       [118130.48300279],
       [119995.13826549],
       [128355.52189699],
       [102709.73316172],
       [230749.84986731],
       [246315.54051076],
       [124415.03177364],
       [106433.47736096],
       [161143.37153759],
       [166191.85055548],
       [148036.80245085],
       [171645.47818238],
       [238886.90640113],
       [325463.59707843],
       [144906.98504323],
       [148368.07144472],
       [169318.08051853],
       [184921.66341436],
       [326783.69729713],
       [ 95285.32815223],
       [235091.82229031],
       [ 71899.12216381],
       [162102.42737206],
       [ 93799.30279758],
       [350116.26178279],
       [195197.8110861 ],
       [183250.15654554],
       [127243.54393936],
       [196585.84621657],
       [480081.6170212 ],
       [152079.34391781],
       [146659.07903283],
       [ 87321.58883396],
       [374566.08393593],
       [195256.30901334],
       [131361.10424536],
       [141279.32479891],
       [110096.0877276 ],
       [218677.35466099],
       [337394.00166592],
       [141089.04468278],
       [194147.22549329],
       [229307.45420367],
       [141898.58520348],
       [136305.94314714],
       [ 88592.16282129],
       [108907.56244623],
       [261378.8172183 ],
       [121227.04541913],
       [147478.36780592],
       [168966.4617152 ],
       [249074.63134816],
       [199619.11266407],
       [221814.7097073 ],
       [293373.88440875],
       [179481.79399091],
       [121634.88058015],
       [441484.82200036],
       [144974.70486143],
       [119655.65619538],
       [175617.67710837],
       [198990.76299499],
       [177621.12434186],
       [129740.9414245 ],
       [191295.825782  ],
       [216863.72285959],
       [ 96030.98720854],
       [114583.09394083],
       [241641.90557254],
       [455606.72183098],
       [143311.43554512],
       [101340.69835445],
       [318992.54928007],
       [182854.18210654],
       [364608.76280564],
       [331377.57298631],
       [320705.67890477],
       [174125.77460433],
       [135337.12517932],
       [356810.35446702],
       [117142.71349392],
       [136154.79571799],
       [129711.24146087],
       [252408.76356712],
       [140526.01114377],
       [207642.88934842],
       [138275.49093092],
       [176600.23956187],
       [155852.08133283],
       [226344.02460059],
       [200730.30100757],
       [170774.95915225],
       [248926.60782105],
       [116123.97774667],
       [197041.30990724],
       [150401.88124761],
       [126748.58332423],
       [160772.96428917],
       [ 83753.79307753],
       [142530.35904959],
       [151186.74050313],
       [134851.17869854],
       [ 50562.38398887],
       [227443.10200753],
       [192847.35178569],
       [140929.69319924],
       [100760.3474043 ],
       [122280.62720862],
       [119642.25979599],
       [131415.31574016],
       [ 58442.70567354],
       [145997.52188314],
       [247069.15554663],
       [240105.44833803],
       [219892.00988983],
       [104210.64777697],
       [124485.5032654 ],
       [443094.1480765 ],
       [267955.33466444],
       [238456.54299985],
       [167576.8105825 ],
       [163598.76367179],
       [266662.88798151],
       [206001.00683383],
       [465351.64372039],
       [138440.808867  ],
       [160737.63814591],
       [145982.53414716],
       [206191.55664921],
       [164241.18638384],
       [104110.31958516],
       [150817.38567217],
       [ 64631.90742402],
       [163050.75368792],
       [133034.30500497],
       [201468.6017029 ],
       [252224.16623689],
       [198164.25443232],
       [161933.46364605],
       [113690.57150015],
       [213055.11592194],
       [183212.28314545],
       [128810.27639882],
       [ 57713.42034637],
       [183358.16260316],
       [125880.73455937],
       [122022.92761336],
       [113371.95338434],
       [196574.89394643],
       [153434.80103226],
       [298296.62105809],
       [128830.84440616],
       [116256.32321991],
       [105592.93920162],
       [291684.71893881],
       [186168.87098857],
       [127860.22115399],
       [189602.45436176],
       [121377.74878877],
       [117225.63885533],
       [135617.08991409],
       [138137.60223256],
       [238874.62467829],
       [221820.57896013],
       [189520.00581294],
       [210248.32100931],
       [113841.78185754],
       [279586.57926556],
       [241271.1245101 ],
       [207574.70862599],
       [209690.33438169],
       [156482.18514425],
       [110808.19357437],
       [170689.5458836 ],
       [178070.5118314 ],
       [123255.24229957],
       [187388.6595238 ],
       [198105.94434886],
       [137593.19070093],
       [113356.14394489],
       [244484.37413709],
       [216019.61992325],
       [148897.38248887],
       [292211.4239973 ],
       [166291.94537806],
       [ 58203.54236114],
       [154705.62142789],
       [ 85572.99597186],
       [298248.79613931],
       [169813.75315448],
       [ 92682.97839488],
       [405222.61829341],
       [308078.68168064],
       [180018.7947706 ],
       [250614.05884285],
       [172779.86060332],
       [314648.9060853 ],
       [222965.64760149],
       [313333.42244185],
       [267394.32708145],
       [113835.40438028],
       [119714.21237309],
       [166902.128858  ],
       [296911.53690811],
       [302272.05375398],
       [133312.51008746],
       [235539.14500786],
       [218669.81611987],
       [200605.46030256],
       [ 97444.6443181 ],
       [ 83228.31353647],
       [411782.62676582],
       [225080.71042795],
       [253293.92633058],
       [204813.60213081],
       [132771.48906044],
       [101530.4186881 ],
       [155137.70388234],
       [240394.77876948],
       [158552.45322418],
       [132383.79976272],
       [217012.62786682],
       [175006.8538568 ],
       [137816.78196616],
       [202346.10979596],
       [201867.77085773],
       [181683.65308436],
       [337629.48393283],
       [117714.14965419],
       [139860.95864879],
       [148565.01411558],
       [183127.90269734],
       [107240.19346193],
       [109431.78935444],
       [237736.70295639],
       [124539.59650993],
       [118593.77405404],
       [ 97450.29754171],
       [142870.73449013],
       [252551.25786843],
       [213990.61489939],
       [ 94665.57011523],
       [100332.74182063],
       [130833.07068171],
       [104958.10558994],
       [123830.57462937],
       [ 64391.13827448],
       [113283.32548744],
       [143921.41082257],
       [155327.65027216],
       [211069.05014415],
       [271584.68982596],
       [250480.16288023],
       [178796.57354183],
       [181249.22926268],
       [318614.54694814],
       [122974.6759899 ],
       [149633.41830607],
       [ 85099.58761904],
       [111735.13960192],
       [195897.76515755],
       [220134.74206876],
       [132958.83392144],
       [116099.85310401],
       [209468.61998184],
       [248281.02346803],
       [237977.70270122],
       [283114.53807233],
       [131443.73855818],
       [386656.92797046],
       [395967.38806751],
       [291841.10154602],
       [227286.60397354],
       [114258.97112488],
       [ 63667.45194355],
       [108719.31683626],
       [171083.6681251 ],
       [280068.33122967],
       [139768.80688104],
       [111346.06287463],
       [154337.32726901],
       [185267.77592199],
       [185088.82736056],
       [132952.3574885 ],
       [160199.55396289],
       [187083.45675006],
       [150854.72784414],
       [195377.91206896],
       [107461.25912756],
       [178920.78128412],
       [100957.32208175],
       [127746.76509222],
       [131369.50624431],
       [178543.28513337],
       [185672.29790966],
       [106575.76113764],
       [137611.11109331],
       [179112.94512149],
       [299659.80491975],
       [235556.0479507 ],
       [170550.35238657],
       [ 99688.16140955],
       [227514.75367777],
       [164367.97333646],
       [144859.57643111],
       [169031.03013905],
       [105083.28298442],
       [284905.34205567],
       [131401.73289097],
       [261220.99614125],
       [162324.49633874],
       [221178.00791979],
       [246662.21144325],
       [117472.47945577],
       [137566.77913758],
       [134712.62427921],
       [ 70956.46530376],
       [151663.66197739],
       [204042.31501393],
       [287483.68678132],
       [208623.49147014],
       [209185.17675358],
       [205638.2588853 ],
       [111241.11455822],
       [204318.52987535],
       [ 92566.06010669],
       [155518.80067058],
       [383145.8758556 ],
       [128221.96639089],
       [300196.81802148],
       [185861.41749912],
       [277474.957551  ],
       [236911.16051865],
       [123314.91405991],
       [156905.0025968 ],
       [125810.30599179],
       [342659.8218361 ],
       [333484.29789681],
       [227751.49013124],
       [187392.68565868],
       [161059.14781985],
       [221204.61863317],
       [117582.60704539],
       [122782.95026075],
       [ 88841.54060829],
       [294539.83142278],
       [156633.85073946],
       [111648.34632893],
       [180673.27633697],
       [ 89291.63518595],
       [197602.76621344],
       [203843.14876279],
       [140166.48082269],
       [ 85835.31035816],
       [203827.4810822 ],
       [230450.53297103],
       [132839.17250326],
       [294687.65641393],
       [145089.01872535],
       [139850.44269045],
       [148917.97957547],
       [225254.05147423],
       [308016.72787879],
       [136768.82534524],
       [125444.56780395],
       [150566.66794327],
       [241610.53160804],
       [127930.76123127],
       [257033.4462667 ],
       [346224.51634848],
       [116367.75261788],
       [216613.45191531],
       [108947.75305738],
       [167144.23012254],
       [237177.16983729],
       [105333.85299884],
       [236343.84344461],
       [123840.29749139],
       [209525.22145021],
       [384804.18275991],
       [199711.72337756],
       [213824.38925218],
       [134169.89716699],
       [288954.82504807],
       [115026.42736628],
       [135290.44657523],
       [125512.02901231],
       [203399.85259232],
       [ 89133.61451035],
       [336422.89912143],
       [224599.21528585],
       [166667.01570651],
       [135163.69999272],
       [143190.65050938],
       [202069.11027466],
       [134476.56010412],
       [111924.07421137],
       [177554.22502301],
       [160715.6036323 ],
       [210913.76711463],
       [ 43463.48594676],
       [ 99990.67937876],
       [306576.11836386],
       [151370.57498111],
       [229351.41462828],
       [279143.07803241],
       [254450.20858029],
       [188751.88044501],
       [200853.71278887],
       [227248.79583027],
       [231746.05893681],
       [116554.0411213 ],
       [246129.9221148 ],
       [114560.61940326],
       [142955.13534973],
       [126455.46763557],
       [147918.97521784],
       [494285.18008207],
       [126521.99904772],
       [226438.6907396 ],
       [245111.21987584],
       [219665.24136336],
       [ 95115.90879128],
       [128443.63085153],
       [142409.47412104],
       [246853.11390032],
       [188855.17730777],
       [106490.74590686],
       [253405.63571365],
       [211361.3943652 ],
       [105642.8956977 ],
       [146292.66223387],
       [100090.01124571],
       [206040.65841002],
       [ 66697.9295088 ],
       [213445.84469322],
       [101092.9484856 ],
       [190730.79925949],
       [322463.56883848],
       [145763.11972225],
       [164836.22259266],
       [195029.39159471],
       [177831.61596047],
       [143291.62563832],
       [149821.72446452],
       [213021.22080002],
       [173396.39941463],
       [226042.56048214],
       [380470.89072569],
       [166353.11060191],
       [ 93740.14688883],
       [123151.96180112],
       [180669.90427954],
       [106309.24659934],
       [181205.58957368],
       [233466.54224184],
       [204872.2670678 ],
       [146976.00670983],
       [254933.84929131],
       [129752.19791437],
       [275751.59451766],
       [ 96487.7864288 ],
       [ 94253.84036213],
       [248849.60517534],
       [118101.12372342],
       [108382.32828658],
       [127526.412745  ],
       [151131.59926485],
       [ 41192.74497638],
       [191646.90603901],
       [160605.93480972],
       [192981.0618418 ],
       [273872.97211273],
       [281661.05921858],
       [107739.10914208],
       [127005.98616314],
       [122099.36298398],
       [120793.17048032],
       [221015.96862519],
       [413676.83926329],
       [194607.9017504 ],
       [110069.39621268],
       [131829.70101966],
       [ 54898.6009954 ],
       [104213.85380997],
       [227094.75783924],
       [150000.71439685],
       [191315.69008042],
       [168989.21452691],
       [123632.00322771],
       [ 62613.94322984],
       [230526.75543536],
       [134912.8036981 ],
       [157003.03076532],
       [145966.18897236],
       [ 86251.73243677],
       [ 68436.69920909],
       [112787.45077469],
       [238711.9622552 ],
       [341419.62125959],
       [242000.92973855],
       [117490.21793119],
       [ 85864.05370262],
       [313252.77957605],
       [137829.66800266],
       [302852.23439407],
       [ 81902.82672707],
       [183008.76662917],
       [220209.86858723],
       [ 75655.33860064],
       [ 90325.51432949],
       [137216.99599266],
       [115058.62855977],
       [176814.27246847],
       [109363.54864783],
       [143344.51336342],
       [182570.27674607],
       [127658.56981666],
       [118925.88159242],
       [133635.32231175],
       [126307.21192575],
       [198400.12889369],
       [121795.34479784],
       [158755.03220747],
       [151427.75624892],
       [126332.53394145],
       [ 90778.20664119],
       [141820.81605325],
       [171236.54820021],
       [128209.83867413],
       [184084.90039217],
       [148728.44714792],
       [203789.3688136 ],
       [118695.74852495],
       [154794.70929145],
       [152803.53604856],
       [292306.90875516],
       [115734.41439386],
       [148370.7649762 ],
       [167984.80465386],
       [149192.49288356],
       [123995.58095803],
       [283830.23644598],
       [222148.88617042],
       [134903.87357696],
       [113956.4743969 ],
       [132709.43612332],
       [129345.10070035],
       [325698.78769686],
       [219304.28170306],
       [143883.34629646],
       [134453.71864514],
       [ 92778.99514597],
       [386893.95545535],
       [122930.48943706],
       [198946.57280591],
       [120475.27874524],
       [184361.68069249],
       [237967.36001962],
       [ 94953.87217811],
       [132809.74045591],
       [119074.55305421],
       [165967.46019484],
       [117493.92682027],
       [113365.584533  ],
       [351923.57285993],
       [227673.18621364],
       [148126.47580813],
       [140942.08858245],
       [ 23797.74634332],
       [222198.73928024],
       [281638.61004225],
       [ 62957.04375563],
       [177561.76145288],
       [217408.02269757],
       [106324.67055476],
       [145308.87622204],
       [107348.36107481],
       [151669.66594968],
       [151827.63088016],
       [197630.22312158],
       [121730.58481371],
       [327078.95400416],
       [153167.08084986],
       [184769.28273866],
       [186574.00291818],
       [131778.05167986],
       [ 76728.47297516],
       [146939.29861242],
       [191466.1621738 ],
       [129640.39018448],
       [160339.34223188],
       [135048.43912114],
       [150681.7916688 ],
       [313383.82539115],
       [138355.57807619],
       [215085.77565483],
       [267620.53065571],
       [150231.7427887 ],
       [ 63905.25441896],
       [230941.81850024],
       [179347.98708294],
       [121919.8853544 ],
       [166611.51594785],
       [156220.86656294],
       [116479.39001092],
       [ 99065.84917038],
       [150627.51168738],
       [ 63961.56344903],
       [158957.59295865],
       [211350.96223156],
       [161217.1905756 ],
       [280311.11092813],
       [178050.2735189 ],
       [160894.3507573 ],
       [162488.39671554],
       [174434.82392371],
       [227115.86313881],
       [387274.41692801],
       [226593.08591057],
       [200179.21867637],
       [181296.68699458],
       [159402.31878881],
       [269874.96854024],
       [220972.49223997],
       [230558.37741296],
       [252565.54316589],
       [141838.42324193],
       [121892.09504882],
       [138176.57204644],
       [130276.9714466 ],
       [ 67546.58387649],
       [142046.93439655],
       [105187.15889965],
       [345596.52562439],
       [204069.35068715],
       [165416.14241829],
       [231050.14133989],
       [196021.87413417],
       [159755.81979877],
       [207761.4434496 ],
       [405179.69041767],
       [173853.85551272],
       [166582.86276317],
       [ 70279.44174429],
       [120158.74678231],
       [302353.7441145 ],
       [130081.74618214],
       [223577.23222647],
       [161930.95466799],
       [220053.09974748],
       [359856.06669946],
       [ 95190.6209038 ],
       [251092.81240815],
       [159133.06028911],
       [144803.94033638],
       [141568.32667148],
       [103871.02463306],
       [283861.2172526 ],
       [284860.04585413],
       [156200.42797673],
       [127209.25397904],
       [ 99309.04697745],
       [321582.86361275],
       [215397.61940028],
       [110114.45830716],
       [135468.04639785],
       [127253.70307126],
       [127138.6936483 ],
       [188252.90525578],
       [288498.51407886],
       [207531.3260695 ],
       [190750.46431835],
       [249940.78694664],
       [220335.37434883],
       [248713.76300094],
       [137196.72779841],
       [102181.69471947],
       [314834.79319008],
       [197557.35162685],
       [190111.60273419],
       [141320.0325128 ],
       [283575.94371397],
       [ 85783.26743892],
       [241601.77362064],
       [183009.01959387],
       [246782.70211435],
       [136994.91805989],
       [197586.57169492],
       [148727.32773655],
       [141790.25554879],
       [156018.35779924],
       [147158.99592078],
       [124244.43848019],
       [224404.01250426],
       [182422.53361913],
       [155828.03578421],
       [105363.43275641],
       [183305.78159566],
       [169726.44244722],
       [187714.24558656],
       [216911.83002708],
       [110693.85789174],
       [315743.40734104],
       [236450.84796181],
       [138011.59364503],
       [137711.13491998],
       [166255.60226364],
       [153496.82599706],
       [111107.36001227],
       [428802.10042501],
       [ 87605.91640381],
       [151323.0375143 ],
       [245977.61582302],
       [140533.96701   ],
       [215313.12173329],
       [131825.06018232],
       [237448.96991668],
       [148297.68647846],
       [303934.63670415],
       [181108.64168103],
       [212663.56473337],

In [81]:
lr_df = test[["SalePrice"]].copy()
lr_df.head()

          SalePrice
Id
2658  120766.510897
2718  146783.696766
2414  240476.794384
1989  129448.265157
625   173758.446508

In [82]:
lr_df["SalePrice"] = lr_pred
lr_df.head()

          SalePrice
Id
2658  119277.688746
2718  147413.313990
2414  241741.877044
1989  129813.963262
625   173653.003392

In [83]:
lr_df.to_csv("./datasets/submission_lr.csv", index=True)

Please refer to the readme for the final Kaggle scores